generator:
  class: sfPropelGenerator
  param:
    model_class:           Mes
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Mes
    plural:                Mess
    route_prefix:          mes
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        nombre: { label: "Mes" }
      list:
        title: false
        display: [=nombre]
        batch_actions: {}
        object_actions: {}
        max_per_page: 10
        actions:
          _new:
            label: Agregar mes
      filter:    ~
      form:    ~
      edit:
        title: false
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver