generator:
  class: sfPropelGenerator
  param:
    model_class:           ProductoTienda
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ProductoTienda
    plural:                ProductoTiendas
    route_prefix:          producto_tienda
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
