generator:
  class: sfPropelGenerator
  param:
    model_class:           Lista
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Lista
    plural:                Listas
    route_prefix:          lista
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id_alumno: { label: Alumno}
        alumno_no_control: { label: No control}
        id_curso: { label: Curso}
        _alumno: { label: Nombre alumno }
        primera_calificacion_examen: { label: 1er examen }
        calificacion_parcial: { label: Calificacion parcial }
        segunda_calificacion_examen: { label: 2do examen }
        calificacion_final: { label: Calificacion Final }
      list:
        title: Alumno de %%id%%
        display: [alumno_no_control, =_alumno, fecha_inscripcion, primera_calificacion_examen,calificacion_parcial,segunda_calificacion_examen,calificacion_final, inasistencia, aprobado]
        batch_actions: {}
        object_actions:
          print:
            label: imprimir
        max_per_page: 30
        actions: 
          imprimir:
            label: Imprimir
          cerrar:
            label: Cerrar
      filter:
          display: [ id_alumno, id_curso, aprobado]
      form:  ~
      edit:
        title: %%alumno%% (%%curso%%)
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver