generator:
  class: sfPropelGenerator
  param:
    model_class:           Curso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Curso
    plural:                Cursos
    route_prefix:          curso_lista_profesor
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id_alumno: { label: Alumno}
        alumno_no_control: { label: No control}
        id_curso: { label: Curso}
        _alumno: { label: Nombre alumno }
        primera_calificacion_examen: { label: Examen bimestral }
        calificacion_parcial: { label: Promedio bimestral }
        segunda_calificacion_examen: { label: Examen parcial }
        calificacion_final: { label: Promedio }
        curso: {label: Curso asignado}
      list:
        title: false
        batch_actions: {}
        actions: {}
        display: [Materia, Periodo, anno, Salon]
        max_per_page: 30
      filter:
        display: [id_materia, id_periodo, anno]
      form:    ~
      edit:    ~
      new:     ~