generator:
  class: sfPropelGenerator
  param:
    model_class:           Curso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Curso
    plural:                Cursos
    route_prefix:          curso
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: { label: "Clave" }
        id_materia: { label: "Nivel" }
        id_profesor: { label: "Profesor" }
        id_periodo: { label: "Periodo" }
        id_salon: { label: "Salón" }
        hora_inicio: { label: "Hora inicio" }
        hora_final: { label: "Hora final" }
        anno: { label: "Año" }
      list:
        title: false
        display: [=materia, inscritos, profesor, periodo, salon, anno, estado]
        batch_actions: {}
        object_actions:
          ImprimirLista:
            label: Imprimir Lista
        max_per_page: 10
        actions:
          _new:
            label: Agregar Curso
      filter:
       display: [id_materia, id_profesor, id_periodo, id_salon, anno]
      form:    ~
      edit:
        title: false
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver
