generator:
  class: sfPropelGenerator
  param:
    model_class:           Curso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Curso
    plural:                Cursos
    route_prefix:          curso
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: { label: "Clave" }
        id_materia: { label: "Materia" }
        id_profesor: { label: "Profesor" }
        id_periodo: { label: "Periodo" }
        id_salon_lunes: { label: "Salón Lunes" }
        id_salon_martes: { label: "Salón Martes" }
        id_salon_miercoles: { label: "Salón Miercoles" }
        id_salon_jueves: { label: "Salón Jueves" }
        id_salon_viernes: { label: "Salón Viernes" }
        hora_inicio: { label: "Hora inicio" }
        hora_final: { label: "Hora final" }
        anno: { label: "Año" }
      list:
        title: false
        display: [=materia, inscritos, profesor, periodo, salon_lunes,salon_martes,salon_miercoles,salon_jueves, salon_viernes, anno, estado]
        batch_actions: {}
        object_actions:
          ImprimirListaCalificacion:
            label: Imprimir Lista Calificacion
          ImprimirLista:
            label: Imprimir Lista
        max_per_page: 10
        actions:
          _new:
            label: Agregar Curso
      filter:
       display: [id_materia, id_profesor, id_periodo, id_salon_lunes,id_salon_martes, id_salon_miercoles,id_salon_jueves, id_salon_viernes,anno, estado]
      form:    ~
      edit:
        title: false
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver
