default:
  is_secure: true
  credentials: [[academico,secretaria]]

ImprimirLista:
  credentials: [[academico, secretaria, profesor]] 
  
ImprimirCalificacionLista:
  credentials: [[academico, secretaria, profesor]] 