generator:
  class: sfPropelGenerator
  param:
    model_class:           Profesor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Profesor
    plural:                Profesors
    route_prefix:          profesor
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        rfc : { label: CURP, help: CURP. XXXX###### }
        a_paterno: { label: Apellido Paterno }
        a_materno: { label: Apellido Materno }
        cp: { label: Código Postal }
        email: { label: Correo Electrónico, help: juan.perez@example.com }
        telefono: { label: Teléfono, help: "###-###-####" }
        direccion: { label: Dirección }
      list:
        title: false
        max_per_page: 30
        batch_actions: {}
        object_actions: {}
        display: [=rfc, nombre, a_paterno, a_materno, telefono, e_mail]
        actions:
          _new:
            label: Agregar Profesor
      filter:
        display: [rfc, nombre, a_paterno, a_materno, activo]
        fields:
          rfc : { label: RFC, help: '' }
      form:    ~
      edit:
        title: false
        actions:
            _save:
              label: Guardar
            _delete:
              label: Eliminar
            _list:
              label: Volver
      new:
        title: false
        actions:
            _save:
              label: Guardar
            _save_and_add:
              label: Guardar y Agregar otro
            _list:
              label: Volver