generator:
  class: sfPropelGenerator
  param:
    model_class:           Salon
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Salon
    plural:                Salons
    route_prefix:          salon
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        salon: { label: "Salon" }
      list:
        title: false
        display: [=salon]
        batch_actions: {}
        object_actions:
          ImprimirHorario:
            label: Imprimir horario del salon.
        max_per_page: 10
        actions:
          _new:
            label: Agregar salon
      filter:    ~
      form:    ~
      edit:
        title: %%salon%%
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver
