generator:
  class: sfPropelGenerator
  param:
    model_class:           WkBook
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              WkBook
    plural:                WkBooks
    route_prefix:          wk_book
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        id_decimal:        { label: Clasification }
        title:             { label: Title of the Book}
        author_firstname:  { label: Author name  }
        author_lastname:   { label: Author lastname }
        year:              { label: Year  }
        publishing_house:  { label: Publishing house  }
        isbn:              { label: ISBN }
      list:    
        title: Catalog of Books Hno Wokaty
        display: [id_decimal,title, author_firstname, author_lastname, volume, dewey_number, isbn, heresy, year, primary_subject, quantity]
        fields:  
        max_per_page: 50
      filter:  
        display: [id_decimal, title, author_firstname, author_lastname, dewey_number, isbn, year, primary_subject, heresy]
      form:    ~
      edit:    
        title: Edit book  %%title%% of %%author_firstname%%
        fields:  
           title:             { label: Title }
           author_firstname:  { label: Name  }
           author_lastname:   { label: Lastname }
           year:              { label: Year  }
           publishing_house:  { label: Publishing house  }
           isbn:              { label: ISBN }
      new:
        title: New book
