generator:
  class: sfPropelGenerator
  param:
    model_class:           WkBook
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              WkBook
    plural:                WkBooks
    route_prefix:          wk_book
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id_decimal:        { label: Clasification }
        deweyn:            { label: Dewey Number }
        decimalen:         { label: Tema }
        title:             { label: Title of the Book}
        author_firstname:  { label: Author name  }
        author_lastname:   { label: Author lastname }
        year:              { label: Year  }
        publishing_house:  { label: Publishing house  }
        isbn:              { label: ISBN }
        name:              { label: Full name }
      list:
        title: Catalog of Books Hno Wokaty
        display: [=Clasification,title, =name, volume, deweyn, isbn, heresy, year, primary_subject, quantity]
        fields:
        max_per_page: 25
      filter:
        display: [id_decimal, title, author_firstname, author_lastname, isbn, year, primary_subject, heresy]
      form:    ~
      edit:
        title: Edit book  %%title%% of %%author_firstname%%
        fields:
           title:             { label: Title }
           author_firstname:  { label: Name  }
           author_lastname:   { label: Lastname }
           year:              { label: Year  }
           publishing_house:  { label: Publishing house  }
           isbn:              { label: ISBN }
      new:
        title: New book
