wk_book_consult_wkbook:
  class: sfPropelRouteCollection
  options:
    model:                WkBook
    module:               consult_wkbook
    prefix_path:          /consult_wkbook
    column:               id
    with_wildcard_routes: true

book_consult_book:
  class: sfPropelRouteCollection
  options:
    model:                Book
    module:               consult_book
    prefix_path:          /consult_book
    column:               id
    with_wildcard_routes: true

libro_consulta_libro:
  class: sfPropelRouteCollection
  options:
    model:                Libro
    module:               consulta_libro
    prefix_path:          /consulta_libro
    column:               id
    with_wildcard_routes: true

libro:
  class: sfPropelRouteCollection
  options:
    model:                Libro
    module:               libros
    prefix_path:          /libros
    column:               id
    with_wildcard_routes: true

entero:
  class: sfPropelRouteCollection
  options:
    model:                Entero
    module:               numeros_dewey
    prefix_path:          /numeros_dewey
    column:               id
    with_wildcard_routes: true

decimal:
  class: sfPropelRouteCollection
  options:
    model:                Decimal
    module:               decimal_dewey
    prefix_path:          /decimal_dewey
    column:               id
    with_wildcard_routes: true

book:
  class: sfPropelRouteCollection
  options:
    model:                Book
    module:               books
    prefix_path:          /books
    column:               id
    with_wildcard_routes: true

wk_book:
  class: sfPropelRouteCollection
  options:
    model:                WkBook
    module:               wokaty_books
    prefix_path:          /wokaty_books
    column:               id
    with_wildcard_routes: true

integer:
  class: sfPropelRouteCollection
  options:
    model:                Integer
    module:               numbers_dewey
    prefix_path:          /numbers_dewey
    column:               id
    with_wildcard_routes: true

decimalen:
  class: sfPropelRouteCollection
  options:
    model:                Decimalen
    module:               decimal_english_dewey
    prefix_path:          /decimal_english_dewey
    column:               id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: ipe, action: index }

legal:
  url:   /
  param: { module: ipe, action: index }

about:
  url:   /
  param: { module: ipe, action: index }

download_manual:
  url:   /download/manual.:sf_format
  param: { module: ipe, action: DownloadManual, sf_format: pdf}

##
###
#

libro_detalles:
  url:              /consulta_libro/detalles/:id.:sf_format
  class:            sfPropelRoute
  options:          { model: Libro, type: object, method: getLibro }
  requirements:
    id:             \d+
    sf_method:      [get]
  param:            { module: Libro, action: Detalles, sf_format: html }

#
#
#
#
change_password:
  url:              /changepassword
  param:            { module: ipe, action: ChangePasswordShow }
change_password_do:
  url:              /dochangepassword
  param:            { module: ipe, action: ChangePassword }

recover_password:
  url:              /recoverpassword
  param:            { module: ipe, action: RecoverPasswordShow }
recover_password_do:
  url:              /dorecoverpassword
  param:            { module: ipe, action: RecoverPassword }


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }