

#################################ADMIN GENERATOR################################

profesor:
  class: sfPropelRouteCollection
  options:
    model:                Profesor
    module:               profesor
    prefix_path:          /profesor
    column:               id
    with_wildcard_routes: true

curso:
  class: sfPropelRouteCollection
  options:
    model:                Curso
    module:               curso
    prefix_path:          /curso
    column:               id
    with_wildcard_routes: true

materia:
  class: sfPropelRouteCollection
  options:
    model:                Materia
    module:               materia
    prefix_path:          /materia
    column:               id
    with_wildcard_routes: true

periodo:
  class: sfPropelRouteCollection
  options:
    model:                Periodo
    module:               periodo
    prefix_path:          /periodo
    column:               id
    with_wildcard_routes: true

salon:
  class: sfPropelRouteCollection
  options:
    model:                Salon
    module:               salon
    prefix_path:          /salon
    column:               id
    with_wildcard_routes: true

alumno:
  class: sfPropelRouteCollection
  options:
    model:                Alumno
    module:               alumno
    prefix_path:          /alumno
    column:               id
    with_wildcard_routes: true

lista:
  class: sfPropelRouteCollection
  options:
    model:                Lista
    module:               lista
    prefix_path:          /curso_secretaria/lista
    column:               id
    with_wildcard_routes: true

mes:
  class: sfPropelRouteCollection
  options:
    model:                Mes
    module:               mes
    prefix_path:          /mes
    column:               id
    with_wildcard_routes: true

curso:
  class: sfPropelRouteCollection
  options:
    model:                Curso
    module:               curso
    prefix_path:          /curso
    column:               id
    with_wildcard_routes: true
    with_wildcard_routes: true

curso_curso_secretaria:
  class: sfPropelRouteCollection
  options:
    model:                Curso
    module:               curso_secretaria
    prefix_path:          ca/curso_secretaria
    column:               id
    with_wildcard_routes: true


##########################Admin Generator Biblioteca#########################

libro:
  class: sfPropelRouteCollection
  options:
    model:                Libro
    module:               libros
    prefix_path:          /libros
    column:               id
    with_wildcard_routes: true

book:
  class: sfPropelRouteCollection
  options:
    model:                Book
    module:               books
    prefix_path:          /books
    column:               id
    with_wildcard_routes: true

wk_book:
  class: sfPropelRouteCollection
  options:
    model:                WkBook
    module:               wokaty_books
    prefix_path:          /wokaty_books
    column:               id
    with_wildcard_routes: true

integer:
  class: sfPropelRouteCollection
  options:
    model:                Integer
    module:               numbers_dewey
    prefix_path:          /numbers_dewey
    column:               id
    with_wildcard_routes: true

entero:
  class: sfPropelRouteCollection
  options:
    model:                Entero
    module:               numeros_dewey
    prefix_path:          /numeros_dewey
    column:               id
    with_wildcard_routes: true

decimal:
  class: sfPropelRouteCollection
  options:
    model:                Decimal
    module:               decimal_dewey
    prefix_path:          /decimal_dewey
    column:               id
    with_wildcard_routes: true

decimalen:
  class: sfPropelRouteCollection
  options:
    model:                Decimalen
    module:               decimal_english_dewey
    prefix_path:          /decimal_english_dewey
    column:               id
    with_wildcard_routes: true

############################Admin Generator Tienda#########################

venta_tienda:
  class: sfPropelRouteCollection
  options:
    model:                VentaTienda
    module:               venta
    prefix_path:          /venta
    column:               id
    with_wildcard_routes: true

producto_tienda:
  class: sfPropelRouteCollection
  options:
    model:                ProductoTienda
    module:               producto
    prefix_path:          /producto
    column:               id
    with_wildcard_routes: true

empleado_tienda:
  class: sfPropelRouteCollection
  options:
    model:                EmpleadoTienda
    module:               empleado
    prefix_path:          /empleado
    column:               id
    with_wildcard_routes: true

compra_tienda:
  class: sfPropelRouteCollection
  options:
    model:                CompraTienda
    module:               compra
    prefix_path:          /compra
    column:               id
    with_wildcard_routes: true



##################################Inicio#################################

homepage:
  url:   /
  param: { module: ipe, action: index }

legal:
  url:   /
  param: { module: ipe, action: index }

about:
  url:   /
  param: { module: ipe, action: index }

download_manual:
  url:   /download/manual.:sf_format
  param: { module: ipe, action: DownloadManual, sf_format: pdf}

##########################Detalles Libros##################################

wk_book_consult_wkbook:
  class: sfPropelRouteCollection
  options:
    model:                WkBook
    module:               consult_wkbook
    prefix_path:          /consult_wkbook
    column:               id
    with_wildcard_routes: true

book_consult_book:
  class: sfPropelRouteCollection
  options:
    model:                Book
    module:               consult_book
    prefix_path:          /consult_book
    column:               id
    with_wildcard_routes: true

libro_consulta_libro:
  class: sfPropelRouteCollection
  options:
    model:                Libro
    module:               consulta_libro
    prefix_path:          /consulta_libro
    column:               id
    with_wildcard_routes: true

libro_detalles:
  url:              /consulta_libro/detalles/:id.:sf_format
  class:            sfPropelRoute
  options:          { model: Libro, type: object, method: getLibro }
  requirements:
    id:             \d+
    sf_method:      [get]
  param:            { module: Libro, action: Detalles, sf_format: html }

###################################Password(Pendiente)##################
change_password:
  url:              /changepassword
  param:            { module: ipe, action: ChangePasswordShow }
change_password_do:
  url:              /dochangepassword
  param:            { module: ipe, action: ChangePassword }

recover_password:
  url:              /recoverpassword
  param:            { module: ipe, action: RecoverPasswordShow }
recover_password_do:
  url:              /dorecoverpassword
  param:            { module: ipe, action: RecoverPassword }

##################################sfGuardPlugin#################################

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

#################################Custom################################

curso_imprimir_lista_calificacion:
  url:              /curso/imprimir_lista_calificacion/:id.:sf_format
  class:            sfPropelRoute
  options:          { model: Curso, type: object, method: getCurso }
  requirements:
    id:             \d+
    sf_method:      [get]
  param:            { module: curso, action: ImprimirListaCalificacion, sf_format: pdf }
  
lista_list_imprimir:
  url:              /curso/imprimir_lista/:id.:sf_format
  class:            sfPropelRoute
  options:          { model: Curso, type: object, method: getCurso }
  requirements:
    id:             \d+
    sf_method:      [get]
  param:            { module: curso, action: ImprimirLista, sf_format: pdf }

curso_imprimir_lista:
  url:              /curso/imprimir_lista/:id.:sf_format
  class:            sfPropelRoute
  options:          { model: Curso, type: object, method: getCurso }
  requirements:
    id:             \d+
    sf_method:      [get]
  param:            { module: curso, action: ImprimirLista, sf_format: pdf }

lista_capturar:
  url:              /lista/capturar/:id.:sf_format
  class:            sfPropelRoute
  options:          { model: Curso, type: object, method: getCurso }
  requirements:
    id:             \d+
    sf_method:      [get]
  param:            { module: lista, action: CapturarCalificaciones, sf_format: html }

lista_capturar_do:
  url:              /lista/docapturar/:id
  class:            sfPropelRoute
  options:          { model: Curso, type: object, method: getCurso }
  requirements:
    id:             \d+
    sf_method:      [post]
  param:            { module: lista, action: CapturarCalificacionesDo }

lista_cerrar:
  url:              /lista/cerrar/:id.:sf_format
  class:            sfPropelRoute
  options:          { model: Curso, type: object, method: getCurso }
  requirements:
    id:             \d+
    sf_method:      [get]
  param:            { module: lista, action: CerrarLista, sf_format: html }

alumno_eliminar_preinscritos:
  url:              /alumno/eliminar_preinscritos/
  requirements:
    sf_method:      [get]
  param:            { module: alumno, action: EliminarPreinscritos }

#################################PREINSCRIPCION#################################
preinscripcion_index:
  url:              /preinscripcion/index.:sf_format
  param:            { module: preinscripcion, action: index, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_new:
  url:              /preinscripcion/preinscripcion.:sf_format
  param:            { module: preinscripcion, action: new, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_newSolicitarCurso:
  url:              /preinscripcion/solicitar_curso.:sf_format
  param:            { module: preinscripcion, action: newSolicitarCurso, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_create:
  url:              /preinscripcion/dopreinscripcion.:sf_format
  param:            { module: preinscripcion, action: create, sf_format: html }
  requirements:
   sf_method:       [post]
preinscripcion_createSolicitarCurso:
  url:              /preinscripcion/dosolicitar_curso.:sf_format
  param:            { module: preinscripcion, action: createSolicitarCurso, sf_format: html }
  requirements:
   sf_method:       [post]
preinscripcion_success:
  url:              /preinscripcion/fin.:sf_format
  param:            { module: preinscripcion, action: success, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_successSolicitarCurso:
  url:              /preinscripcion/fin_solicitar_curso.:sf_format
  param:            { module: preinscripcion, action: successSolicitarCurso, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_print_itc_dgtyv_ci_01:
  url:              /preinscripcion/cedula.:sf_format
  param:            { module: preinscripcion, action: PrintITC_DGTYV_CI_01, sf_format: html}
  requirements:
   sf_method:       [get]
###########################PREINSCRIPCION SECRETARIA############################
preinscripcion_secretaria_reinscribir_new:
  url:              /alumno/inscripcion/reinscribir.:sf_format
  param:            { module: preinscripcion_secretaria, action: newReinscribir, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_secretaria_reinscribir_create:
  url:              /alumno/inscripcion/doreinscribir.:sf_format
  param:            { module: preinscripcion_secretaria, action: createReinscribir, sf_format: html }
  requirements:
   sf_method:       [post]
preinscripcion_secretaria_reinscribir_success:
  url:              /alumno/inscripcion/fin_reinscribir.:sf_format
  param:            { module: preinscripcion_secretaria, action: successReinscribir, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_secretaria_inscribir_new:
  url:              /alumno/inscripcion/inscribir.:sf_format
  param:            { module: preinscripcion_secretaria, action: newInscribir, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_secretaria_inscribir_create:
  url:              /alumno/inscripcion/doinscribir.:sf_format
  param:            { module: preinscripcion_secretaria, action: createInscribir, sf_format: html }
  requirements:
   sf_method:       [post]
preinscripcion_secretaria_inscribir_success:
  url:              /alumno/inscripcion/fin_inscribir.:sf_format
  param:            { module: preinscripcion_secretaria, action: successInscribir, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_secretaria_registro_new:
  url:              /alumno/inscripcion/registro.:sf_format
  param:            { module: preinscripcion_secretaria, action: newRegistro, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_secretaria_registro_create:
  url:              /alumno/inscripcion/doregistro.:sf_format
  param:            { module: preinscripcion_secretaria, action: createRegistro, sf_format: html }
  requirements:
   sf_method:       [post]
preinscripcion_secretaria_cambiar_curso_new:
  url:              /alumno/inscripcion/cambiar.:sf_format
  param:            { module: preinscripcion_secretaria, action: newCambiar, sf_format: html }
  requirements:
   sf_method:       [get]
preinscripcion_secretaria_cambiar_curso_create:
  url:              /alumno/inscripcion/docambiar.:sf_format
  param:            { module: preinscripcion_secretaria, action: createCambiar, sf_format: html }
  requirements:
   sf_method:       [post]
preinscripcion_secretaria_cambiar_curso_success:
  url:              /alumno/inscripcion/fin_cambiar.:sf_format
  param:            { module: preinscripcion_secretaria, action: successCambiar, sf_format: html }
  requirements:
   sf_method:       [get]


  #################################Profesores################################

profesor_profesor_profesor:
  class: sfPropelRouteCollection
  options:
    model:                Profesor
    module:               profesor_profesor
    prefix_path:          /si/profesor/datos
    column:               id
    with_wildcard_routes: true

curso_lista_profesor:
  class: sfPropelRouteCollection
  options:
    model:                Curso
    module:               lista_profesor
    prefix_path:          /si/profesor/cursos
    column:               id
    with_wildcard_routes: true

#################################Alumnos################################

alumno_alumno_alumno:
  class: sfPropelRouteCollection
  options:
    model:                Alumno
    module:               alumno_alumno
    prefix_path:          /alumno_alumno
    column:               id
    with_wildcard_routes: true

alumno_alumno_lista:
  url:              /si/alumno/calificaciones.:sf_format
  param:            { module: lista_alumno, action: index, sf_format: html }
  requirements:
   sf_method:       [get]





