generator:
  class: sfPropelGenerator
  param:
    model_class:           Libro
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Libro
    plural:                Libros
    route_prefix:          libro
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id_decimal:        { label: Clasificaci칩n  }
        titulo:            { label: Titulo del libro }
        nombreautor:       { label: Nombre de autor }
        apaterno_autor:    { label: Apellido paterno }
        amaterno_autor:    { label: Apellido materno }
        ano_publicacion:   { label: A침o de publicaci칩n }
        editorial:         { label: Editorial }
        isbn:              { label: ISBN }
      list:
        title: Catalogo del libros
        display: [ =clasificacion, numero_dewey, titulo, tomo, =nombrecompleto, ano_publicacion, isbn, herejia, tema_primario, cantidad]
        fields:  
        max_per_page: 25
      filter:  
        display: [id_decimal, numero_dewey, titulo, nombreautor, apaterno_autor, ano_publicacion, isbn, tema_primario, herejia ]
      form:    ~
      edit:    
        title: Editar el libro %%titulo%% de %%nombreautor%%
        fields:  
           isbn:              { label: ISBN }
      new:
        title: A침adir nuevo libro
