generator:
  class: sfPropelGenerator
  param:
    model_class:           Libro
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Libro
    plural:                Libros
    route_prefix:          libro
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id_decimal:        { label: Clasificación Dewey  }
        titulo:            { label: Titulo del libro }
        nombreautor:       { label: Nombre de autor }
        nombrecompleto:    { label: Nombre completo }
        apaterno_autor:    { label: Apellido paterno }
        amaterno_autor:    { label: Apellido materno }
        ano_publicacion:   { label: Escrito }
        editorial:         { label: Editorial }
        isbn:              { label: ISBN }
        fot:               { label: Foto }
        numero_dewey:      { label: Dewey antiguo  }
        dewey:             { label: Dewey New }
      list:
        title: Catalogo del libros
        display: [ =clasificacion, titulo, tomo, =nombrecompleto, numero_dewey, =dewey, ano_publicacion, isbn, editorial, herejia, tema_primario, cantidad, fot, actualizado]
        fields:
        max_per_page: 25
        object_actions:
          moveDown:   { label: "Detalles", action: "detalles" }
          _edit:      ~
      filter:
        display: [id_decimal, numero_dewey, titulo, nombreautor, apaterno_autor, isbn, editorial,tema_primario, herejia ]
      form:    ~
      edit:
        title: Editar el libro %%titulo%% escrito por: %%nombreautor%%
        fields:
           isbn:              { label: ISBN }
      new:
        title: Añadir nuevo libro
