generator:
  class: sfPropelGenerator
  param:
    model_class:           Alumno
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Alumno
    plural:                Alumnos
    route_prefix:          alumno
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        numero_control: { label: "Número de control" }
        a_paterno: { label: "Apellido paterno" }
        a_materno: { label: "Apellido materno" }
        telefono: { label: "Teléfono"}
        email: { label: "Correo electrónico" }
      list:
        title: false
        display: [=numero_control, a_paterno, a_materno, nombre, telefono, email, inscrito]
        batch_actions: {}
        object_actions:
          ImprimirAlumnoKardex:
            label: Imprimir kardex
        max_per_page: 50
        actions:
          eliminarPreinscritos:
            label: Eliminar Alumnos Preinscritos
      filter:
        display: [numero_control, nombre, a_paterno, a_materno, telefono, e_mail, inscrito]
      form:    ~
      edit:
        title: false
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver