generator:
  class: sfPropelGenerator
  param:
    model_class:           Decimal
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Decimal
    plural:                Decimals
    route_prefix:          decimal
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        numero:        { label: Numero decimal  }
        id_entero:     { label: Numeros Generales  }
        nombre:        { label: Nombre decimal  }
        descripcion:   { label: Descripción  }
      list:    
        title: Catalogo de los decimales
        display: [ id_entero, =decimal, nombre, descripcion]
        max_per_page: 50
      filter:  
        display: [id_entero, numero, nombre]
      form:    ~
      edit:    
        title: Editar el decimal  %%numero%% 
      new:     
        title: Nuevo numero decimal