INSERT INTO "integer"("number", name, description) VALUES (001,'Knowledge',null);
INSERT INTO "integer"("number", name, description) VALUES (002,'The book',null);
INSERT INTO "integer"("number", name, description) VALUES (003,'Systems',null);
INSERT INTO "integer"("number", name, description) VALUES (004,'Data processing and computer science',null);
INSERT INTO "integer"("number", name, description) VALUES (005,'Computer programming programs and data',null);
INSERT INTO "integer"("number", name, description) VALUES (006,'Special computer methods',null);
INSERT INTO "integer"("number", name, description) VALUES (007,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (008,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (009,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (010,'Bibliography',null);
INSERT INTO "integer"("number", name, description) VALUES (011,'Bibliographies',null);
INSERT INTO "integer"("number", name, description) VALUES (012,'Bibliographies of individuals',null);
INSERT INTO "integer"("number", name, description) VALUES (013,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (014,'Of anonymous and pseudonymous works',null);
INSERT INTO "integer"("number", name, description) VALUES (015,'Bibliographies of works from specific places',null);
INSERT INTO "integer"("number", name, description) VALUES (016,'Bibliographies of works on specific subjects',null);
INSERT INTO "integer"("number", name, description) VALUES (017,'General subject catalogs',null);
INSERT INTO "integer"("number", name, description) VALUES (018,'Catalogs arranged by author date etc.',null);
INSERT INTO "integer"("number", name, description) VALUES (019,'Dictionary catalogs',null);
INSERT INTO "integer"("number", name, description) VALUES (020,'Library and information sciences',null);
INSERT INTO "integer"("number", name, description) VALUES (021,'Library relationships',null);
INSERT INTO "integer"("number", name, description) VALUES (022,'Administration of physical plant',null);
INSERT INTO "integer"("number", name, description) VALUES (023,'Personnel management',null);
INSERT INTO "integer"("number", name, description) VALUES (024,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (025,'Library operations',null);
INSERT INTO "integer"("number", name, description) VALUES (026,'Libraries for specific subjects',null);
INSERT INTO "integer"("number", name, description) VALUES (027,'General libraries',null);
INSERT INTO "integer"("number", name, description) VALUES (028,'Reading and use of other information media',null);
INSERT INTO "integer"("number", name, description) VALUES (029,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (030,'General encyclopedic works',null);
INSERT INTO "integer"("number", name, description) VALUES (031,'Encyclopedias in American English',null);
INSERT INTO "integer"("number", name, description) VALUES (032,'Encyclopedias in English',null);
INSERT INTO "integer"("number", name, description) VALUES (033,'In other Germanic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (034,'Encyclopedias in French Occitan and Catalan',null);
INSERT INTO "integer"("number", name, description) VALUES (035,'In Italian Romanian and related languages',null);
INSERT INTO "integer"("number", name, description) VALUES (036,'Encyclopedias in Spanish and Portuguese',null);
INSERT INTO "integer"("number", name, description) VALUES (037,'Encyclopedias in Slavic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (038,'Encyclopedias in Scandinavian languages',null);
INSERT INTO "integer"("number", name, description) VALUES (039,'Encyclopedias in other languages',null);
INSERT INTO "integer"("number", name, description) VALUES (040,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (041,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (042,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (043,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (044,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (045,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (046,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (047,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (048,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (049,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (050,'General serial publications',null);
INSERT INTO "integer"("number", name, description) VALUES (051,'Serials in American English',null);
INSERT INTO "integer"("number", name, description) VALUES (052,'Serials in English',null);
INSERT INTO "integer"("number", name, description) VALUES (053,'Serials in other Germanic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (054,'Serials in French Occitan and Catalan',null);
INSERT INTO "integer"("number", name, description) VALUES (055,'In Italian Romanian and related languages',null);
INSERT INTO "integer"("number", name, description) VALUES (056,'Serials in Spanish and Portuguese',null);
INSERT INTO "integer"("number", name, description) VALUES (057,'Serials in Slavic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (058,'Serials in Scandinavian languages',null);
INSERT INTO "integer"("number", name, description) VALUES (059,'Serials in other languages',null);
INSERT INTO "integer"("number", name, description) VALUES (060,'General organizations and museum science',null);
INSERT INTO "integer"("number", name, description) VALUES (061,'Organizations in North America',null);
INSERT INTO "integer"("number", name, description) VALUES (062,'Organizations in British Isles in England',null);
INSERT INTO "integer"("number", name, description) VALUES (063,'Organizations in central Europe in Germany',null);
INSERT INTO "integer"("number", name, description) VALUES (064,'Organizations in France and Monaco',null);
INSERT INTO "integer"("number", name, description) VALUES (065,'Organizations in Italy and adjacent islands',null);
INSERT INTO "integer"("number", name, description) VALUES (066,'In Iberian Peninsula and adjacent islands',null);
INSERT INTO "integer"("number", name, description) VALUES (067,'Organizations in eastern Europe in Russia',null);
INSERT INTO "integer"("number", name, description) VALUES (068,'Organizations in other geographic areas',null);
INSERT INTO "integer"("number", name, description) VALUES (069,'Museum science',null);
INSERT INTO "integer"("number", name, description) VALUES (070,'News media journalism and publishing',null);
INSERT INTO "integer"("number", name, description) VALUES (071,'Newspapers in North America',null);
INSERT INTO "integer"("number", name, description) VALUES (072,'Newspapers in British Isles in England',null);
INSERT INTO "integer"("number", name, description) VALUES (073,'Newspapers in central Europe in Germany',null);
INSERT INTO "integer"("number", name, description) VALUES (074,'Newspapers in France and Monaco',null);
INSERT INTO "integer"("number", name, description) VALUES (075,'Newspapers in Italy and adjacent islands',null);
INSERT INTO "integer"("number", name, description) VALUES (076,'In Iberian Peninsula and adjacent islands',null);
INSERT INTO "integer"("number", name, description) VALUES (077,'Newspapers in eastern Europe in Russia',null);
INSERT INTO "integer"("number", name, description) VALUES (078,'Newspapers in Scandinavia',null);
INSERT INTO "integer"("number", name, description) VALUES (079,'Newspapers in other geographic areas',null);
INSERT INTO "integer"("number", name, description) VALUES (080,'General collections',null);
INSERT INTO "integer"("number", name, description) VALUES (081,'Collections in American English',null);
INSERT INTO "integer"("number", name, description) VALUES (082,'Collections in English',null);
INSERT INTO "integer"("number", name, description) VALUES (083,'Collections in other Germanic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (084,'Collections in French Occitan and Catalan',null);
INSERT INTO "integer"("number", name, description) VALUES (085,'In Italian Romanian and related languages',null);
INSERT INTO "integer"("number", name, description) VALUES (086,'Collections in Spanish and Portuguese',null);
INSERT INTO "integer"("number", name, description) VALUES (087,'Collections in Slavic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (088,'Collections in Scandinavian languages',null);
INSERT INTO "integer"("number", name, description) VALUES (089,'Collections in other languages',null);
INSERT INTO "integer"("number", name, description) VALUES (090,'Manuscripts and rare books',null);
INSERT INTO "integer"("number", name, description) VALUES (091,'Manuscripts',null);
INSERT INTO "integer"("number", name, description) VALUES (092,'Block books',null);
INSERT INTO "integer"("number", name, description) VALUES (093,'Incunabula',null);
INSERT INTO "integer"("number", name, description) VALUES (094,'Printed books',null);
INSERT INTO "integer"("number", name, description) VALUES (095,'Books notable for bindings',null);
INSERT INTO "integer"("number", name, description) VALUES (096,'Books notable for illustrations',null);
INSERT INTO "integer"("number", name, description) VALUES (097,'Books notable for ownership or origin',null);
INSERT INTO "integer"("number", name, description) VALUES (098,'Prohibited works forgeries and hoaxes',null);
INSERT INTO "integer"("number", name, description) VALUES (099,'Books notable for format',null);
INSERT INTO "integer"("number", name, description) VALUES (100,'Philosophy and psychology',null);
INSERT INTO "integer"("number", name, description) VALUES (101,'Theory of philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (102,'Miscellany',null);
INSERT INTO "integer"("number", name, description) VALUES (103,'Dictionaries and encyclopedias',null);
INSERT INTO "integer"("number", name, description) VALUES (104,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (105,'Serial publications',null);
INSERT INTO "integer"("number", name, description) VALUES (106,'Organizations and management',null);
INSERT INTO "integer"("number", name, description) VALUES (107,'Education research and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (108,'Kinds of persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (109,'Historical and collected persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (110,'Metaphysics',null);
INSERT INTO "integer"("number", name, description) VALUES (111,'Ontology',null);
INSERT INTO "integer"("number", name, description) VALUES (112,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (113,'Cosmology',null);
INSERT INTO "integer"("number", name, description) VALUES (114,'Space',null);
INSERT INTO "integer"("number", name, description) VALUES (115,'Time',null);
INSERT INTO "integer"("number", name, description) VALUES (116,'Change',null);
INSERT INTO "integer"("number", name, description) VALUES (117,'Structure',null);
INSERT INTO "integer"("number", name, description) VALUES (118,'Force and energy',null);
INSERT INTO "integer"("number", name, description) VALUES (119,'Number and quantity',null);
INSERT INTO "integer"("number", name, description) VALUES (120,'Epistemology causation and humankind',null);
INSERT INTO "integer"("number", name, description) VALUES (121,'Epistemology',null);
INSERT INTO "integer"("number", name, description) VALUES (122,'Causation',null);
INSERT INTO "integer"("number", name, description) VALUES (123,'Determinism and indeterminism',null);
INSERT INTO "integer"("number", name, description) VALUES (124,'Teleology',null);
INSERT INTO "integer"("number", name, description) VALUES (125,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (126,'The self',null);
INSERT INTO "integer"("number", name, description) VALUES (127,'The unconscious and the subconscious',null);
INSERT INTO "integer"("number", name, description) VALUES (128,'Humankind',null);
INSERT INTO "integer"("number", name, description) VALUES (129,'Origin and destiny of individual souls',null);
INSERT INTO "integer"("number", name, description) VALUES (130,'Parapsychology and occultism',null);
INSERT INTO "integer"("number", name, description) VALUES (131,'Parapsychological and occult methods',null);
INSERT INTO "integer"("number", name, description) VALUES (132,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (133,'Specific topics in parapsychology and occultism',null);
INSERT INTO "integer"("number", name, description) VALUES (134,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (135,'Dreams and mysteries',null);
INSERT INTO "integer"("number", name, description) VALUES (136,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (137,'Divinatory graphology',null);
INSERT INTO "integer"("number", name, description) VALUES (138,'Physiognomy',null);
INSERT INTO "integer"("number", name, description) VALUES (139,'Phrenology',null);
INSERT INTO "integer"("number", name, description) VALUES (140,'Specific philosophical schools',null);
INSERT INTO "integer"("number", name, description) VALUES (141,'Idealism and related systems',null);
INSERT INTO "integer"("number", name, description) VALUES (142,'Critical philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (143,'Bergsonism and intuitionism',null);
INSERT INTO "integer"("number", name, description) VALUES (144,'Humanism and related systems',null);
INSERT INTO "integer"("number", name, description) VALUES (145,'Sensationalism',null);
INSERT INTO "integer"("number", name, description) VALUES (146,'Naturalism and related systems',null);
INSERT INTO "integer"("number", name, description) VALUES (147,'Pantheism and related systems',null);
INSERT INTO "integer"("number", name, description) VALUES (148,'Eclecticism liberalism and traditionalism',null);
INSERT INTO "integer"("number", name, description) VALUES (149,'Other philosophical systems ',null);
INSERT INTO "integer"("number", name, description) VALUES (150,'Psychology',null);
INSERT INTO "integer"("number", name, description) VALUES (151,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (152,'Perception movement emotions and drives',null);
INSERT INTO "integer"("number", name, description) VALUES (153,'Mental processes and intelligence',null);
INSERT INTO "integer"("number", name, description) VALUES (154,'Subconscious and altered states',null);
INSERT INTO "integer"("number", name, description) VALUES (155,'Differential and developmental psychology',null);
INSERT INTO "integer"("number", name, description) VALUES (156,'Comparative psychology',null);
INSERT INTO "integer"("number", name, description) VALUES (157,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (158,'Applied psychology',null);
INSERT INTO "integer"("number", name, description) VALUES (159,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (160,'Logic',null);
INSERT INTO "integer"("number", name, description) VALUES (161,'Induction',null);
INSERT INTO "integer"("number", name, description) VALUES (162,'Deduction',null);
INSERT INTO "integer"("number", name, description) VALUES (163,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (164,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (165,'Fallacies and sources of error',null);
INSERT INTO "integer"("number", name, description) VALUES (166,'Syllogisms',null);
INSERT INTO "integer"("number", name, description) VALUES (167,'Hypotheses',null);
INSERT INTO "integer"("number", name, description) VALUES (168,'Argument and persuasion',null);
INSERT INTO "integer"("number", name, description) VALUES (169,'Analogy',null);
INSERT INTO "integer"("number", name, description) VALUES (170,'Ethics',null);
INSERT INTO "integer"("number", name, description) VALUES (171,'Ethical systems',null);
INSERT INTO "integer"("number", name, description) VALUES (172,'Political ethics',null);
INSERT INTO "integer"("number", name, description) VALUES (173,'Ethics of family relationships',null);
INSERT INTO "integer"("number", name, description) VALUES (174,'Occupational ethics',null);
INSERT INTO "integer"("number", name, description) VALUES (175,'Ethics of recreation and leisure',null);
INSERT INTO "integer"("number", name, description) VALUES (176,'Ethics of sex and reproduction',null);
INSERT INTO "integer"("number", name, description) VALUES (177,'Ethics of social relations',null);
INSERT INTO "integer"("number", name, description) VALUES (178,'Ethics of consumption',null);
INSERT INTO "integer"("number", name, description) VALUES (179,'Other ethical norms',null);
INSERT INTO "integer"("number", name, description) VALUES (180,'Ancient medieval and eastern philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (181,'Eastern philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (182,'Pre-Socratic Greek philosophies',null);
INSERT INTO "integer"("number", name, description) VALUES (183,'Socratic and related philosophies',null);
INSERT INTO "integer"("number", name, description) VALUES (184,'Platonic philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (185,'Aristotelian philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (186,'Skeptic and Neoplatonic philosophies',null);
INSERT INTO "integer"("number", name, description) VALUES (187,'Epicurean philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (188,'Stoic philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (189,'Medieval western philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (190,'Modern western philosophy',null);
INSERT INTO "integer"("number", name, description) VALUES (191,'Philosophy of United States and Canada',null);
INSERT INTO "integer"("number", name, description) VALUES (192,'Philosophy of British Isles',null);
INSERT INTO "integer"("number", name, description) VALUES (193,'Philosophy of Germany and Austria',null);
INSERT INTO "integer"("number", name, description) VALUES (194,'Philosophy of France',null);
INSERT INTO "integer"("number", name, description) VALUES (195,'Philosophy of Italy',null);
INSERT INTO "integer"("number", name, description) VALUES (196,'Philosophy of Spain and Portugal',null);
INSERT INTO "integer"("number", name, description) VALUES (197,'Philosophy of former Soviet Union',null);
INSERT INTO "integer"("number", name, description) VALUES (198,'Philosophy of Scandinavia',null);
INSERT INTO "integer"("number", name, description) VALUES (199,'Philosophy in other geographic areas',null);
INSERT INTO "integer"("number", name, description) VALUES (200,'Religion',null);
INSERT INTO "integer"("number", name, description) VALUES (201,'Religious mythology and social theology',null);
INSERT INTO "integer"("number", name, description) VALUES (202,'Doctrines',null);
INSERT INTO "integer"("number", name, description) VALUES (203,'Public worship and other practices',null);
INSERT INTO "integer"("number", name, description) VALUES (204,'Religious experience life and practice',null);
INSERT INTO "integer"("number", name, description) VALUES (205,'Religious ethics',null);
INSERT INTO "integer"("number", name, description) VALUES (206,'Leaders and organization',null);
INSERT INTO "integer"("number", name, description) VALUES (207,'Missions and religious education',null);
INSERT INTO "integer"("number", name, description) VALUES (208,'Sources',null);
INSERT INTO "integer"("number", name, description) VALUES (209,'Sects and reform movements',null);
INSERT INTO "integer"("number", name, description) VALUES (210,'Philosophy and theory of religion',null);
INSERT INTO "integer"("number", name, description) VALUES (211,'Concepts of God',null);
INSERT INTO "integer"("number", name, description) VALUES (212,'Existence knowability and attributes of God',null);
INSERT INTO "integer"("number", name, description) VALUES (213,'Creation',null);
INSERT INTO "integer"("number", name, description) VALUES (214,'Theodicy',null);
INSERT INTO "integer"("number", name, description) VALUES (215,'Science and religion',null);
INSERT INTO "integer"("number", name, description) VALUES (216,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (217,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (218,'Humankind',null);
INSERT INTO "integer"("number", name, description) VALUES (219,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (220,'Bible',null);
INSERT INTO "integer"("number", name, description) VALUES (221,'Old Testament (Tanakh)',null);
INSERT INTO "integer"("number", name, description) VALUES (222,'Historical books of Old Testament',null);
INSERT INTO "integer"("number", name, description) VALUES (223,'Poetic books of Old Testament',null);
INSERT INTO "integer"("number", name, description) VALUES (224,'Prophetic books of Old Testament',null);
INSERT INTO "integer"("number", name, description) VALUES (225,'New Testament',null);
INSERT INTO "integer"("number", name, description) VALUES (226,'Gospels and Acts',null);
INSERT INTO "integer"("number", name, description) VALUES (227,'Epistles',null);
INSERT INTO "integer"("number", name, description) VALUES (228,'Revelation (Apocalypse)',null);
INSERT INTO "integer"("number", name, description) VALUES (229,'Apocrypha and pseudepigrapha',null);
INSERT INTO "integer"("number", name, description) VALUES (230,'Christianity and Christian theology',null);
INSERT INTO "integer"("number", name, description) VALUES (231,'God',null);
INSERT INTO "integer"("number", name, description) VALUES (232,'Jesus Christ and his family',null);
INSERT INTO "integer"("number", name, description) VALUES (233,'Humankind',null);
INSERT INTO "integer"("number", name, description) VALUES (234,'Salvation and grace',null);
INSERT INTO "integer"("number", name, description) VALUES (235,'Spiritual beings',null);
INSERT INTO "integer"("number", name, description) VALUES (236,'Eschatology',null);
INSERT INTO "integer"("number", name, description) VALUES (237,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (238,'Creeds and catechisms',null);
INSERT INTO "integer"("number", name, description) VALUES (239,'Apologetics and polemics',null);
INSERT INTO "integer"("number", name, description) VALUES (240,'Christian moral and devotional theology',null);
INSERT INTO "integer"("number", name, description) VALUES (241,'Christian ethics',null);
INSERT INTO "integer"("number", name, description) VALUES (242,'Devotional literature',null);
INSERT INTO "integer"("number", name, description) VALUES (243,'Evangelistic writings for individuals',null);
INSERT INTO "integer"("number", name, description) VALUES (244,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (245,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (246,'Use of art in Christianity',null);
INSERT INTO "integer"("number", name, description) VALUES (247,'Church furnishings and articles',null);
INSERT INTO "integer"("number", name, description) VALUES (248,'Christian experience practice and life',null);
INSERT INTO "integer"("number", name, description) VALUES (249,'Christian observances in family life',null);
INSERT INTO "integer"("number", name, description) VALUES (250,'Christian orders and local church',null);
INSERT INTO "integer"("number", name, description) VALUES (251,'Preaching',null);
INSERT INTO "integer"("number", name, description) VALUES (252,'Texts of sermons',null);
INSERT INTO "integer"("number", name, description) VALUES (253,'Pastoral office and work',null);
INSERT INTO "integer"("number", name, description) VALUES (254,'Parish administration',null);
INSERT INTO "integer"("number", name, description) VALUES (255,'Religious congregations and orders',null);
INSERT INTO "integer"("number", name, description) VALUES (256,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (257,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (258,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (259,'Pastoral care of families and kinds of persons',null);
INSERT INTO "integer"("number", name, description) VALUES (260,'Social and ecclesiastical theology',null);
INSERT INTO "integer"("number", name, description) VALUES (261,'Social theology',null);
INSERT INTO "integer"("number", name, description) VALUES (262,'Ecclesiology',null);
INSERT INTO "integer"("number", name, description) VALUES (263,'Days times and places of observance',null);
INSERT INTO "integer"("number", name, description) VALUES (264,'Public worship',null);
INSERT INTO "integer"("number", name, description) VALUES (265,'Sacraments other rites and acts',null);
INSERT INTO "integer"("number", name, description) VALUES (266,'Missions',null);
INSERT INTO "integer"("number", name, description) VALUES (267,'Associations for religious work',null);
INSERT INTO "integer"("number", name, description) VALUES (268,'Religious education',null);
INSERT INTO "integer"("number", name, description) VALUES (269,'Spiritual renewal',null);
INSERT INTO "integer"("number", name, description) VALUES (270,'History of Christianity and Christian church',null);
INSERT INTO "integer"("number", name, description) VALUES (271,'Religious orders in church history',null);
INSERT INTO "integer"("number", name, description) VALUES (272,'Persecutions in church history',null);
INSERT INTO "integer"("number", name, description) VALUES (273,'Doctrinal controversies and heresies',null);
INSERT INTO "integer"("number", name, description) VALUES (274,'History of Christianity in Europe',null);
INSERT INTO "integer"("number", name, description) VALUES (275,'History of Christianity in Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (276,'History of Christianity in Africa',null);
INSERT INTO "integer"("number", name, description) VALUES (277,'History of Christianity in North America',null);
INSERT INTO "integer"("number", name, description) VALUES (278,'History of Christianity in South America',null);
INSERT INTO "integer"("number", name, description) VALUES (279,'History of Christianity in other areas',null);
INSERT INTO "integer"("number", name, description) VALUES (280,'Christian denominations and sects',null);
INSERT INTO "integer"("number", name, description) VALUES (281,'Early church and Eastern churches',null);
INSERT INTO "integer"("number", name, description) VALUES (282,'Roman Catholic Church',null);
INSERT INTO "integer"("number", name, description) VALUES (283,'Anglican churches',null);
INSERT INTO "integer"("number", name, description) VALUES (284,'Protestants of Continental origin',null);
INSERT INTO "integer"("number", name, description) VALUES (285,'Presbyterian Reformed and Congregational',null);
INSERT INTO "integer"("number", name, description) VALUES (286,'Baptist Disciples of Christ and Adventist',null);
INSERT INTO "integer"("number", name, description) VALUES (287,'Methodist and related churches',null);
INSERT INTO "integer"("number", name, description) VALUES (288,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (289,'Other denominations and sects',null);
INSERT INTO "integer"("number", name, description) VALUES (290,'Other religions',null);
INSERT INTO "integer"("number", name, description) VALUES (291,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (292,'Greek and Roman religion',null);
INSERT INTO "integer"("number", name, description) VALUES (293,'Germanic religion',null);
INSERT INTO "integer"("number", name, description) VALUES (294,'Religions of Indic origin',null);
INSERT INTO "integer"("number", name, description) VALUES (295,'Zoroastrianism',null);
INSERT INTO "integer"("number", name, description) VALUES (296,'Judaism',null);
INSERT INTO "integer"("number", name, description) VALUES (297,'Islam Babism and Bahai Faith',null);
INSERT INTO "integer"("number", name, description) VALUES (298,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (299,'Religions not provided for elsewhere',null);
INSERT INTO "integer"("number", name, description) VALUES (300,'Social sciences',null);
INSERT INTO "integer"("number", name, description) VALUES (301,'Sociology and anthropology',null);
INSERT INTO "integer"("number", name, description) VALUES (302,'Social interaction',null);
INSERT INTO "integer"("number", name, description) VALUES (303,'Social processes',null);
INSERT INTO "integer"("number", name, description) VALUES (304,'Factors affecting social behavior',null);
INSERT INTO "integer"("number", name, description) VALUES (305,'Social groups',null);
INSERT INTO "integer"("number", name, description) VALUES (306,'Culture and institutions',null);
INSERT INTO "integer"("number", name, description) VALUES (307,'Communities',null);
INSERT INTO "integer"("number", name, description) VALUES (308,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (309,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (310,'Collections of general statistics',null);
INSERT INTO "integer"("number", name, description) VALUES (311,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (312,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (313,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (314,'General statistics of Europe',null);
INSERT INTO "integer"("number", name, description) VALUES (315,'General statistics of Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (316,'General statistics of Africa',null);
INSERT INTO "integer"("number", name, description) VALUES (317,'General statistics of North America',null);
INSERT INTO "integer"("number", name, description) VALUES (318,'General statistics of South America',null);
INSERT INTO "integer"("number", name, description) VALUES (319,'General statistics of other areas',null);
INSERT INTO "integer"("number", name, description) VALUES (320,'Political science',null);
INSERT INTO "integer"("number", name, description) VALUES (321,'Systems of governments and states',null);
INSERT INTO "integer"("number", name, description) VALUES (322,'Relation of state to organized groups',null);
INSERT INTO "integer"("number", name, description) VALUES (323,'Civil and political rights',null);
INSERT INTO "integer"("number", name, description) VALUES (324,'The political process',null);
INSERT INTO "integer"("number", name, description) VALUES (325,'International migration and colonization',null);
INSERT INTO "integer"("number", name, description) VALUES (326,'Slavery and emancipation',null);
INSERT INTO "integer"("number", name, description) VALUES (327,'International relations',null);
INSERT INTO "integer"("number", name, description) VALUES (328,'The legislative process',null);
INSERT INTO "integer"("number", name, description) VALUES (329,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (330,'Economics',null);
INSERT INTO "integer"("number", name, description) VALUES (331,'Labor economics',null);
INSERT INTO "integer"("number", name, description) VALUES (332,'Financial economics',null);
INSERT INTO "integer"("number", name, description) VALUES (333,'Economics of land and energy',null);
INSERT INTO "integer"("number", name, description) VALUES (334,'Cooperatives',null);
INSERT INTO "integer"("number", name, description) VALUES (335,'Socialism and related systems',null);
INSERT INTO "integer"("number", name, description) VALUES (336,'Public finance',null);
INSERT INTO "integer"("number", name, description) VALUES (337,'International economics',null);
INSERT INTO "integer"("number", name, description) VALUES (338,'Production',null);
INSERT INTO "integer"("number", name, description) VALUES (339,'Macroeconomics and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (340,'Law',null);
INSERT INTO "integer"("number", name, description) VALUES (341,'Law of nations',null);
INSERT INTO "integer"("number", name, description) VALUES (342,'Constitutional and administrative law',null);
INSERT INTO "integer"("number", name, description) VALUES (343,'Military tax trade and industrial law',null);
INSERT INTO "integer"("number", name, description) VALUES (344,'Labor social education and cultural law',null);
INSERT INTO "integer"("number", name, description) VALUES (345,'Criminal law',null);
INSERT INTO "integer"("number", name, description) VALUES (346,'Private law',null);
INSERT INTO "integer"("number", name, description) VALUES (347,'Civil procedure and courts',null);
INSERT INTO "integer"("number", name, description) VALUES (348,'Laws regulations and cases',null);
INSERT INTO "integer"("number", name, description) VALUES (349,'Law of specific jurisdictions and areas',null);
INSERT INTO "integer"("number", name, description) VALUES (350,'Public administration and military science',null);
INSERT INTO "integer"("number", name, description) VALUES (351,'Public administration',null);
INSERT INTO "integer"("number", name, description) VALUES (352,'General considerations of public administration',null);
INSERT INTO "integer"("number", name, description) VALUES (353,'Specific fields of public administration',null);
INSERT INTO "integer"("number", name, description) VALUES (354,'Administration of economy and environment',null);
INSERT INTO "integer"("number", name, description) VALUES (355,'Military science',null);
INSERT INTO "integer"("number", name, description) VALUES (356,'Infantry forces and warfare',null);
INSERT INTO "integer"("number", name, description) VALUES (357,'Mounted forces and warfare',null);
INSERT INTO "integer"("number", name, description) VALUES (358,'Air and other specialized forces',null);
INSERT INTO "integer"("number", name, description) VALUES (359,'Sea forces and warfare',null);
INSERT INTO "integer"("number", name, description) VALUES (360,'Social problems and services associations',null);
INSERT INTO "integer"("number", name, description) VALUES (361,'Social problems and social welfare in general',null);
INSERT INTO "integer"("number", name, description) VALUES (362,'Social welfare problems and services',null);
INSERT INTO "integer"("number", name, description) VALUES (363,'Other social problems and services',null);
INSERT INTO "integer"("number", name, description) VALUES (364,'Criminology',null);
INSERT INTO "integer"("number", name, description) VALUES (365,'Penal and related institutions',null);
INSERT INTO "integer"("number", name, description) VALUES (366,'Associations',null);
INSERT INTO "integer"("number", name, description) VALUES (367,'General clubs',null);
INSERT INTO "integer"("number", name, description) VALUES (368,'Insurance',null);
INSERT INTO "integer"("number", name, description) VALUES (369,'Miscellaneous kinds of associations',null);
INSERT INTO "integer"("number", name, description) VALUES (370,'Education',null);
INSERT INTO "integer"("number", name, description) VALUES (371,'Schools and their activities special education',null);
INSERT INTO "integer"("number", name, description) VALUES (372,'Elementary education',null);
INSERT INTO "integer"("number", name, description) VALUES (373,'Secondary education',null);
INSERT INTO "integer"("number", name, description) VALUES (374,'Adult education',null);
INSERT INTO "integer"("number", name, description) VALUES (375,'Curricula',null);
INSERT INTO "integer"("number", name, description) VALUES (376,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (377,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (378,'Higher education',null);
INSERT INTO "integer"("number", name, description) VALUES (379,'Public policy issues in education',null);
INSERT INTO "integer"("number", name, description) VALUES (380,'Commerce communications and transportation',null);
INSERT INTO "integer"("number", name, description) VALUES (381,'Commerce',null);
INSERT INTO "integer"("number", name, description) VALUES (382,'International commerce',null);
INSERT INTO "integer"("number", name, description) VALUES (383,'Postal communication',null);
INSERT INTO "integer"("number", name, description) VALUES (384,'Communications telecommunication',null);
INSERT INTO "integer"("number", name, description) VALUES (385,'Railroad transportation',null);
INSERT INTO "integer"("number", name, description) VALUES (386,'Inland waterway and ferry transportation',null);
INSERT INTO "integer"("number", name, description) VALUES (387,'Water air and space transportation',null);
INSERT INTO "integer"("number", name, description) VALUES (388,'Transportation ground transportation',null);
INSERT INTO "integer"("number", name, description) VALUES (389,'Metrology and standardization',null);
INSERT INTO "integer"("number", name, description) VALUES (390,'Customs etiquette and folklore',null);
INSERT INTO "integer"("number", name, description) VALUES (391,'Costume and personal appearance',null);
INSERT INTO "integer"("number", name, description) VALUES (392,'Customs of life cycle and domestic life',null);
INSERT INTO "integer"("number", name, description) VALUES (393,'Death customs',null);
INSERT INTO "integer"("number", name, description) VALUES (394,'General customs',null);
INSERT INTO "integer"("number", name, description) VALUES (395,'Etiquette (Manners)',null);
INSERT INTO "integer"("number", name, description) VALUES (396,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (397,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (398,'Folklore',null);
INSERT INTO "integer"("number", name, description) VALUES (399,'Customs of war and diplomacy',null);
INSERT INTO "integer"("number", name, description) VALUES (400,'Language',null);
INSERT INTO "integer"("number", name, description) VALUES (401,'Philosophy and theory',null);
INSERT INTO "integer"("number", name, description) VALUES (402,'Miscellany',null);
INSERT INTO "integer"("number", name, description) VALUES (403,'Dictionaries and encyclopedias',null);
INSERT INTO "integer"("number", name, description) VALUES (404,'Special topics',null);
INSERT INTO "integer"("number", name, description) VALUES (405,'Serial publications',null);
INSERT INTO "integer"("number", name, description) VALUES (406,'Organizations and management',null);
INSERT INTO "integer"("number", name, description) VALUES (407,'Education research and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (408,'Kinds of persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (409,'Geographic and persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (410,'Linguistics',null);
INSERT INTO "integer"("number", name, description) VALUES (411,'Writing systems',null);
INSERT INTO "integer"("number", name, description) VALUES (412,'Etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (413,'Dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (414,'Phonology and phonetics',null);
INSERT INTO "integer"("number", name, description) VALUES (415,'Grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (416,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (417,'Dialectology and historical linguistics',null);
INSERT INTO "integer"("number", name, description) VALUES (418,'Standard usage and applied linguistics',null);
INSERT INTO "integer"("number", name, description) VALUES (419,'Sign languages',null);
INSERT INTO "integer"("number", name, description) VALUES (420,'English and Old English',null);
INSERT INTO "integer"("number", name, description) VALUES (421,'English writing system and phonology',null);
INSERT INTO "integer"("number", name, description) VALUES (422,'English etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (423,'English dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (424,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (425,'English grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (426,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (427,'English language variations',null);
INSERT INTO "integer"("number", name, description) VALUES (428,'Standard English usage',null);
INSERT INTO "integer"("number", name, description) VALUES (429,'Old English (Anglo-Saxon)',null);
INSERT INTO "integer"("number", name, description) VALUES (430,'Germanic languages German',null);
INSERT INTO "integer"("number", name, description) VALUES (431,'German writing systems and phonology',null);
INSERT INTO "integer"("number", name, description) VALUES (432,'German etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (433,'German dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (434,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (435,'German grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (436,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (437,'German language variations',null);
INSERT INTO "integer"("number", name, description) VALUES (438,'Standard German usage',null);
INSERT INTO "integer"("number", name, description) VALUES (439,'Other Germanic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (440,'Romance languages French',null);
INSERT INTO "integer"("number", name, description) VALUES (441,'French writing systems and phonology',null);
INSERT INTO "integer"("number", name, description) VALUES (442,'French etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (443,'French dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (444,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (445,'French grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (446,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (447,'French language variations',null);
INSERT INTO "integer"("number", name, description) VALUES (448,'Standard French usage',null);
INSERT INTO "integer"("number", name, description) VALUES (449,'Occitan and Catalan',null);
INSERT INTO "integer"("number", name, description) VALUES (450,'Italian Romanian and related languages',null);
INSERT INTO "integer"("number", name, description) VALUES (451,'Italian writing systems and phonology',null);
INSERT INTO "integer"("number", name, description) VALUES (452,'Italian etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (453,'Italian dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (454,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (455,'Italian grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (456,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (457,'Italian language variations',null);
INSERT INTO "integer"("number", name, description) VALUES (458,'Standard Italian usage',null);
INSERT INTO "integer"("number", name, description) VALUES (459,'Romanian and related languages',null);
INSERT INTO "integer"("number", name, description) VALUES (460,'Spanish and Portuguese languages',null);
INSERT INTO "integer"("number", name, description) VALUES (461,'Spanish writing systems and phonology',null);
INSERT INTO "integer"("number", name, description) VALUES (462,'Spanish etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (463,'Spanish dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (464,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (465,'Spanish grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (466,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (467,'Spanish language variations',null);
INSERT INTO "integer"("number", name, description) VALUES (468,'Standard Spanish usage',null);
INSERT INTO "integer"("number", name, description) VALUES (469,'Portuguese',null);
INSERT INTO "integer"("number", name, description) VALUES (470,'Italic languages Latin',null);
INSERT INTO "integer"("number", name, description) VALUES (471,'Classical Latin writing and phonology',null);
INSERT INTO "integer"("number", name, description) VALUES (472,'Classical Latin etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (473,'Classical Latin dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (474,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (475,'Classical Latin grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (476,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (477,'Old postclassical and Vulgar Latin',null);
INSERT INTO "integer"("number", name, description) VALUES (478,'Classical Latin usage',null);
INSERT INTO "integer"("number", name, description) VALUES (479,'Other Italic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (480,'Hellenic languages classical Greek',null);
INSERT INTO "integer"("number", name, description) VALUES (481,'Classical Greek writing and phonology',null);
INSERT INTO "integer"("number", name, description) VALUES (482,'Classical Greek etymology',null);
INSERT INTO "integer"("number", name, description) VALUES (483,'Classical Greek dictionaries',null);
INSERT INTO "integer"("number", name, description) VALUES (484,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (485,'Classical Greek grammar',null);
INSERT INTO "integer"("number", name, description) VALUES (486,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (487,'Preclassical and postclassical Greek',null);
INSERT INTO "integer"("number", name, description) VALUES (488,'Classical Greek usage',null);
INSERT INTO "integer"("number", name, description) VALUES (489,'Other Hellenic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (490,'Other languages',null);
INSERT INTO "integer"("number", name, description) VALUES (491,'East Indo-European and Celtic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (492,'Afro-Asiatic languages Semitic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (493,'Non-Semitic Afro-Asiatic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (494,'Altaic Uralic Hyperborean and Dravidian',null);
INSERT INTO "integer"("number", name, description) VALUES (495,'Languages of East and Southeast Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (496,'African languages',null);
INSERT INTO "integer"("number", name, description) VALUES (497,'North American native languages',null);
INSERT INTO "integer"("number", name, description) VALUES (498,'South American native languages',null);
INSERT INTO "integer"("number", name, description) VALUES (499,'Austronesian and other languages',null);
INSERT INTO "integer"("number", name, description) VALUES (500,'Natural Sciences and Mathemetics',null);
INSERT INTO "integer"("number", name, description) VALUES (501,'Philosophy and theory',null);
INSERT INTO "integer"("number", name, description) VALUES (502,'Miscellany',null);
INSERT INTO "integer"("number", name, description) VALUES (503,'Dictionaries and encyclopedias',null);
INSERT INTO "integer"("number", name, description) VALUES (504,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (505,'Serial publications',null);
INSERT INTO "integer"("number", name, description) VALUES (506,'Organizations and management',null);
INSERT INTO "integer"("number", name, description) VALUES (507,'Education research and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (508,'Natural history',null);
INSERT INTO "integer"("number", name, description) VALUES (509,'Historical geographic and persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (510,'Mathematics',null);
INSERT INTO "integer"("number", name, description) VALUES (511,'General principles of mathematics',null);
INSERT INTO "integer"("number", name, description) VALUES (512,'Algebra',null);
INSERT INTO "integer"("number", name, description) VALUES (513,'Arithmetic',null);
INSERT INTO "integer"("number", name, description) VALUES (514,'Topology',null);
INSERT INTO "integer"("number", name, description) VALUES (515,'Analysis',null);
INSERT INTO "integer"("number", name, description) VALUES (516,'Geometry',null);
INSERT INTO "integer"("number", name, description) VALUES (517,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (518,'Numerical analysis',null);
INSERT INTO "integer"("number", name, description) VALUES (519,'Probabilities and applied mathematics',null);
INSERT INTO "integer"("number", name, description) VALUES (520,'Astronomy and allied sciences',null);
INSERT INTO "integer"("number", name, description) VALUES (521,'Celestial mechanics',null);
INSERT INTO "integer"("number", name, description) VALUES (522,'Techniques equipment and materials',null);
INSERT INTO "integer"("number", name, description) VALUES (523,'Specific celestial bodies and phenomena',null);
INSERT INTO "integer"("number", name, description) VALUES (524,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (525,'Earth (Astronomical geography)',null);
INSERT INTO "integer"("number", name, description) VALUES (526,'Mathematical geography',null);
INSERT INTO "integer"("number", name, description) VALUES (527,'Celestial navigation',null);
INSERT INTO "integer"("number", name, description) VALUES (528,'Ephemerides',null);
INSERT INTO "integer"("number", name, description) VALUES (529,'Chronology',null);
INSERT INTO "integer"("number", name, description) VALUES (530,'Physics',null);
INSERT INTO "integer"("number", name, description) VALUES (531,'Classical mechanics solid mechanics',null);
INSERT INTO "integer"("number", name, description) VALUES (532,'Fluid mechanics liquid mechanics',null);
INSERT INTO "integer"("number", name, description) VALUES (533,'Gas mechanics',null);
INSERT INTO "integer"("number", name, description) VALUES (534,'Sound and related vibrations',null);
INSERT INTO "integer"("number", name, description) VALUES (535,'Light and infrared and ultraviolet phenomena',null);
INSERT INTO "integer"("number", name, description) VALUES (536,'Heat',null);
INSERT INTO "integer"("number", name, description) VALUES (537,'Electricity and electronics',null);
INSERT INTO "integer"("number", name, description) VALUES (538,'Magnetism',null);
INSERT INTO "integer"("number", name, description) VALUES (539,'Modern physics',null);
INSERT INTO "integer"("number", name, description) VALUES (540,'Chemistry and allied sciences',null);
INSERT INTO "integer"("number", name, description) VALUES (541,'Physical chemistry',null);
INSERT INTO "integer"("number", name, description) VALUES (542,'Techniques equipment and materials',null);
INSERT INTO "integer"("number", name, description) VALUES (543,'Analytical chemistry',null);
INSERT INTO "integer"("number", name, description) VALUES (544,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (545,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (546,'Inorganic chemistry',null);
INSERT INTO "integer"("number", name, description) VALUES (547,'Organic chemistry',null);
INSERT INTO "integer"("number", name, description) VALUES (548,'Crystallography',null);
INSERT INTO "integer"("number", name, description) VALUES (549,'Mineralogy',null);
INSERT INTO "integer"("number", name, description) VALUES (550,'Earth sciences',null);
INSERT INTO "integer"("number", name, description) VALUES (551,'Geology hydrology and meteorology',null);
INSERT INTO "integer"("number", name, description) VALUES (552,'Petrology',null);
INSERT INTO "integer"("number", name, description) VALUES (553,'Economic geology',null);
INSERT INTO "integer"("number", name, description) VALUES (554,'Earth sciences of Europe',null);
INSERT INTO "integer"("number", name, description) VALUES (555,'Earth sciences of Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (556,'Earth sciences of Africa',null);
INSERT INTO "integer"("number", name, description) VALUES (557,'Earth sciences of North America',null);
INSERT INTO "integer"("number", name, description) VALUES (558,'Earth sciences of South America',null);
INSERT INTO "integer"("number", name, description) VALUES (559,'Earth sciences of other areas',null);
INSERT INTO "integer"("number", name, description) VALUES (560,'Paleontology paleozoology',null);
INSERT INTO "integer"("number", name, description) VALUES (561,'Paleobotany fossil microorganisms',null);
INSERT INTO "integer"("number", name, description) VALUES (562,'Fossil invertebrates',null);
INSERT INTO "integer"("number", name, description) VALUES (563,'Fossil marine and seashore invertebrates',null);
INSERT INTO "integer"("number", name, description) VALUES (564,'Fossil mollusks and molluscoids',null);
INSERT INTO "integer"("number", name, description) VALUES (565,'Fossil arthropods',null);
INSERT INTO "integer"("number", name, description) VALUES (566,'Fossil chordates',null);
INSERT INTO "integer"("number", name, description) VALUES (567,'Fossil cold-blooded vertebrates fossil fishes',null);
INSERT INTO "integer"("number", name, description) VALUES (568,'Fossil birds',null);
INSERT INTO "integer"("number", name, description) VALUES (569,'Fossil mammals',null);
INSERT INTO "integer"("number", name, description) VALUES (570,'Life sciences biology',null);
INSERT INTO "integer"("number", name, description) VALUES (571,'Physiology and related subjects',null);
INSERT INTO "integer"("number", name, description) VALUES (572,'Biochemistry',null);
INSERT INTO "integer"("number", name, description) VALUES (573,'Specific physiological systems in animals',null);
INSERT INTO "integer"("number", name, description) VALUES (574,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (575,'Specific parts of and systems in plants',null);
INSERT INTO "integer"("number", name, description) VALUES (576,'Genetics and evolution',null);
INSERT INTO "integer"("number", name, description) VALUES (577,'Ecology',null);
INSERT INTO "integer"("number", name, description) VALUES (578,'Natural history of organisms',null);
INSERT INTO "integer"("number", name, description) VALUES (579,'Microorganisms fungi and algae',null);
INSERT INTO "integer"("number", name, description) VALUES (580,'Plants (Botany)',null);
INSERT INTO "integer"("number", name, description) VALUES (581,'Specific topics in natural history',null);
INSERT INTO "integer"("number", name, description) VALUES (582,'Plants noted for characteristics and flowers',null);
INSERT INTO "integer"("number", name, description) VALUES (583,'Dicotyledons',null);
INSERT INTO "integer"("number", name, description) VALUES (584,'Monocotyledons',null);
INSERT INTO "integer"("number", name, description) VALUES (585,'Gymnosperms conifers',null);
INSERT INTO "integer"("number", name, description) VALUES (586,'Seedless plants',null);
INSERT INTO "integer"("number", name, description) VALUES (587,'Vascular seedless plants',null);
INSERT INTO "integer"("number", name, description) VALUES (588,'Bryophytes',null);
INSERT INTO "integer"("number", name, description) VALUES (589,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (590,'Animals (Zoology)',null);
INSERT INTO "integer"("number", name, description) VALUES (591,'Specific topics in natural history',null);
INSERT INTO "integer"("number", name, description) VALUES (592,'Invertebrates',null);
INSERT INTO "integer"("number", name, description) VALUES (593,'Marine and seashore invertebrates',null);
INSERT INTO "integer"("number", name, description) VALUES (594,'Mollusks and molluscoids',null);
INSERT INTO "integer"("number", name, description) VALUES (595,'Arthropods',null);
INSERT INTO "integer"("number", name, description) VALUES (596,'Chordates',null);
INSERT INTO "integer"("number", name, description) VALUES (597,'Cold-blooded vertebrates fishes',null);
INSERT INTO "integer"("number", name, description) VALUES (598,'Birds',null);
INSERT INTO "integer"("number", name, description) VALUES (599,'Mammals',null);
INSERT INTO "integer"("number", name, description) VALUES (600,'Technology',null);
INSERT INTO "integer"("number", name, description) VALUES (601,'Philosophy and theory',null);
INSERT INTO "integer"("number", name, description) VALUES (602,'Miscellany',null);
INSERT INTO "integer"("number", name, description) VALUES (603,'Dictionaries and encyclopedias',null);
INSERT INTO "integer"("number", name, description) VALUES (604,'Special topics',null);
INSERT INTO "integer"("number", name, description) VALUES (605,'Serial publications',null);
INSERT INTO "integer"("number", name, description) VALUES (606,'Organizations',null);
INSERT INTO "integer"("number", name, description) VALUES (607,'Education research and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (608,'Inventions and patents',null);
INSERT INTO "integer"("number", name, description) VALUES (609,'Historical geographic and persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (610,'Medicine and health',null);
INSERT INTO "integer"("number", name, description) VALUES (611,'Human anatomy cytology and histology',null);
INSERT INTO "integer"("number", name, description) VALUES (612,'Human physiology',null);
INSERT INTO "integer"("number", name, description) VALUES (613,'Personal health and safety',null);
INSERT INTO "integer"("number", name, description) VALUES (614,'Incidence and prevention of disease',null);
INSERT INTO "integer"("number", name, description) VALUES (615,'Pharmacology and therapeutics',null);
INSERT INTO "integer"("number", name, description) VALUES (616,'Diseases',null);
INSERT INTO "integer"("number", name, description) VALUES (617,'Surgery and related medical specialties',null);
INSERT INTO "integer"("number", name, description) VALUES (618,'Gynecology obstetrics pediatrics and geriatrics',null);
INSERT INTO "integer"("number", name, description) VALUES (619,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (620,'Engineering and allied operations',null);
INSERT INTO "integer"("number", name, description) VALUES (621,'Applied physics',null);
INSERT INTO "integer"("number", name, description) VALUES (622,'Mining and related operations',null);
INSERT INTO "integer"("number", name, description) VALUES (623,'Military and nautical engineering',null);
INSERT INTO "integer"("number", name, description) VALUES (624,'Civil engineering',null);
INSERT INTO "integer"("number", name, description) VALUES (625,'Engineering of railroads and roads',null);
INSERT INTO "integer"("number", name, description) VALUES (626,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (627,'Hydraulic engineering',null);
INSERT INTO "integer"("number", name, description) VALUES (628,'Sanitary and municipal engineering',null);
INSERT INTO "integer"("number", name, description) VALUES (629,'Other branches of engineering',null);
INSERT INTO "integer"("number", name, description) VALUES (630,'Agriculture and related technologies',null);
INSERT INTO "integer"("number", name, description) VALUES (631,'Techniques equipment and materials',null);
INSERT INTO "integer"("number", name, description) VALUES (632,'Plant injuries diseases and pests',null);
INSERT INTO "integer"("number", name, description) VALUES (633,'Field and plantation crops',null);
INSERT INTO "integer"("number", name, description) VALUES (634,'Orchards fruits and forestry',null);
INSERT INTO "integer"("number", name, description) VALUES (635,'Garden crops (Horticulture)',null);
INSERT INTO "integer"("number", name, description) VALUES (636,'Animal husbandry',null);
INSERT INTO "integer"("number", name, description) VALUES (637,'Processing dairy and related products',null);
INSERT INTO "integer"("number", name, description) VALUES (638,'Insect culture',null);
INSERT INTO "integer"("number", name, description) VALUES (639,'Hunting fishing and conservation',null);
INSERT INTO "integer"("number", name, description) VALUES (640,'Home and family management',null);
INSERT INTO "integer"("number", name, description) VALUES (641,'Food and drink',null);
INSERT INTO "integer"("number", name, description) VALUES (642,'Meals and table service',null);
INSERT INTO "integer"("number", name, description) VALUES (643,'Housing and household equipment',null);
INSERT INTO "integer"("number", name, description) VALUES (644,'Household utilities',null);
INSERT INTO "integer"("number", name, description) VALUES (645,'Household furnishings',null);
INSERT INTO "integer"("number", name, description) VALUES (646,'Sewing clothing and personal living',null);
INSERT INTO "integer"("number", name, description) VALUES (647,'Management of public households',null);
INSERT INTO "integer"("number", name, description) VALUES (648,'Housekeeping',null);
INSERT INTO "integer"("number", name, description) VALUES (649,'Child rearing and home care of persons',null);
INSERT INTO "integer"("number", name, description) VALUES (650,'Management and auxiliary services',null);
INSERT INTO "integer"("number", name, description) VALUES (651,'Office services',null);
INSERT INTO "integer"("number", name, description) VALUES (652,'Processes of written communication',null);
INSERT INTO "integer"("number", name, description) VALUES (653,'Shorthand',null);
INSERT INTO "integer"("number", name, description) VALUES (654,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (655,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (656,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (657,'Accounting',null);
INSERT INTO "integer"("number", name, description) VALUES (658,'General management',null);
INSERT INTO "integer"("number", name, description) VALUES (659,'Advertising and public relations',null);
INSERT INTO "integer"("number", name, description) VALUES (660,'Chemical engineering',null);
INSERT INTO "integer"("number", name, description) VALUES (661,'Industrial chemicals',null);
INSERT INTO "integer"("number", name, description) VALUES (662,'Explosives fuels and related products',null);
INSERT INTO "integer"("number", name, description) VALUES (663,'Beverage technology',null);
INSERT INTO "integer"("number", name, description) VALUES (664,'Food technology',null);
INSERT INTO "integer"("number", name, description) VALUES (665,'Industrial oils fats waxes and gases',null);
INSERT INTO "integer"("number", name, description) VALUES (666,'Ceramic and allied technologies',null);
INSERT INTO "integer"("number", name, description) VALUES (667,'Cleaning color and coating technologies',null);
INSERT INTO "integer"("number", name, description) VALUES (668,'Technology of other organic products',null);
INSERT INTO "integer"("number", name, description) VALUES (669,'Metallurgy',null);
INSERT INTO "integer"("number", name, description) VALUES (670,'Manufacturing',null);
INSERT INTO "integer"("number", name, description) VALUES (671,'Metalworking and primary metal products',null);
INSERT INTO "integer"("number", name, description) VALUES (672,'Iron steel and other iron alloys',null);
INSERT INTO "integer"("number", name, description) VALUES (673,'Nonferrous metals',null);
INSERT INTO "integer"("number", name, description) VALUES (674,'Lumber processing wood products and cork',null);
INSERT INTO "integer"("number", name, description) VALUES (675,'Leather and fur processing',null);
INSERT INTO "integer"("number", name, description) VALUES (676,'Pulp and paper technology',null);
INSERT INTO "integer"("number", name, description) VALUES (677,'Textiles',null);
INSERT INTO "integer"("number", name, description) VALUES (678,'Elastomers and elastomer products',null);
INSERT INTO "integer"("number", name, description) VALUES (679,'Other products of specific materials',null);
INSERT INTO "integer"("number", name, description) VALUES (680,'Manufacture for specific uses',null);
INSERT INTO "integer"("number", name, description) VALUES (681,'Precision instruments and other devices',null);
INSERT INTO "integer"("number", name, description) VALUES (682,'Small forge work (Blacksmithing)',null);
INSERT INTO "integer"("number", name, description) VALUES (683,'Hardware and household appliances',null);
INSERT INTO "integer"("number", name, description) VALUES (684,'Furnishings and home workshops',null);
INSERT INTO "integer"("number", name, description) VALUES (685,'Leather fur goods and related products',null);
INSERT INTO "integer"("number", name, description) VALUES (686,'Printing and related activities',null);
INSERT INTO "integer"("number", name, description) VALUES (687,'Clothing and accessories',null);
INSERT INTO "integer"("number", name, description) VALUES (688,'Other final products and packaging',null);
INSERT INTO "integer"("number", name, description) VALUES (689,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (690,'Buildings',null);
INSERT INTO "integer"("number", name, description) VALUES (691,'Building materials',null);
INSERT INTO "integer"("number", name, description) VALUES (692,'Auxiliary construction practices',null);
INSERT INTO "integer"("number", name, description) VALUES (693,'Specific materials and purposes',null);
INSERT INTO "integer"("number", name, description) VALUES (694,'Wood construction and carpentry',null);
INSERT INTO "integer"("number", name, description) VALUES (695,'Roof covering',null);
INSERT INTO "integer"("number", name, description) VALUES (696,'Utilities',null);
INSERT INTO "integer"("number", name, description) VALUES (697,'Heating ventilating and air-conditioning',null);
INSERT INTO "integer"("number", name, description) VALUES (698,'Detail finishing',null);
INSERT INTO "integer"("number", name, description) VALUES (699,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (700,'The arts fine and decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (701,'Philosophy of fine and decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (702,'Miscellany of fine and decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (703,'Dictionaries of fine and decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (704,'Special topics in fine and decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (705,'Serial publications of fine and decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (706,'Organizations and management',null);
INSERT INTO "integer"("number", name, description) VALUES (707,'Education research and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (708,'Galleries museums and private collections',null);
INSERT INTO "integer"("number", name, description) VALUES (709,'Historical geographic and persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (710,'Civic and landscape art',null);
INSERT INTO "integer"("number", name, description) VALUES (711,'Area planning',null);
INSERT INTO "integer"("number", name, description) VALUES (712,'Landscape architecture',null);
INSERT INTO "integer"("number", name, description) VALUES (713,'Landscape architecture of trafficways',null);
INSERT INTO "integer"("number", name, description) VALUES (714,'Water features',null);
INSERT INTO "integer"("number", name, description) VALUES (715,'Woody plants',null);
INSERT INTO "integer"("number", name, description) VALUES (716,'Herbaceous plants',null);
INSERT INTO "integer"("number", name, description) VALUES (717,'Structures in landscape architecture',null);
INSERT INTO "integer"("number", name, description) VALUES (718,'Landscape design of cemeteries',null);
INSERT INTO "integer"("number", name, description) VALUES (719,'Natural landscapes',null);
INSERT INTO "integer"("number", name, description) VALUES (720,'Architecture',null);
INSERT INTO "integer"("number", name, description) VALUES (721,'Architectural structure',null);
INSERT INTO "integer"("number", name, description) VALUES (722,'Architecture to ca. 300',null);
INSERT INTO "integer"("number", name, description) VALUES (723,'Architecture from ca. 300 to 1399',null);
INSERT INTO "integer"("number", name, description) VALUES (724,'Architecture from 1400',null);
INSERT INTO "integer"("number", name, description) VALUES (725,'Public structures',null);
INSERT INTO "integer"("number", name, description) VALUES (726,'Buildings for religious purposes',null);
INSERT INTO "integer"("number", name, description) VALUES (727,'Buildings for education and research',null);
INSERT INTO "integer"("number", name, description) VALUES (728,'Residential and related buildings',null);
INSERT INTO "integer"("number", name, description) VALUES (729,'Design and decoration',null);
INSERT INTO "integer"("number", name, description) VALUES (730,'Plastic arts sculpture',null);
INSERT INTO "integer"("number", name, description) VALUES (731,'Processes forms and subjects of sculpture',null);
INSERT INTO "integer"("number", name, description) VALUES (732,'Sculpture to ca. 500',null);
INSERT INTO "integer"("number", name, description) VALUES (733,'Greek Etruscan and Roman sculpture',null);
INSERT INTO "integer"("number", name, description) VALUES (734,'Sculpture from ca. 500 to 1399',null);
INSERT INTO "integer"("number", name, description) VALUES (735,'Sculpture from 1400',null);
INSERT INTO "integer"("number", name, description) VALUES (736,'Carving and carvings',null);
INSERT INTO "integer"("number", name, description) VALUES (737,'Numismatics and sigillography',null);
INSERT INTO "integer"("number", name, description) VALUES (738,'Ceramic arts',null);
INSERT INTO "integer"("number", name, description) VALUES (739,'Art metalwork',null);
INSERT INTO "integer"("number", name, description) VALUES (740,'Drawing and decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (741,'Drawing and drawings',null);
INSERT INTO "integer"("number", name, description) VALUES (742,'Perspective',null);
INSERT INTO "integer"("number", name, description) VALUES (743,'Drawing and drawings by subject',null);
INSERT INTO "integer"("number", name, description) VALUES (744,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (745,'Decorative arts',null);
INSERT INTO "integer"("number", name, description) VALUES (746,'Textile arts',null);
INSERT INTO "integer"("number", name, description) VALUES (747,'Interior decoration',null);
INSERT INTO "integer"("number", name, description) VALUES (748,'Glass',null);
INSERT INTO "integer"("number", name, description) VALUES (749,'Furniture and accessories',null);
INSERT INTO "integer"("number", name, description) VALUES (750,'Painting and paintings',null);
INSERT INTO "integer"("number", name, description) VALUES (751,'Techniques equipment materials and forms',null);
INSERT INTO "integer"("number", name, description) VALUES (752,'Color',null);
INSERT INTO "integer"("number", name, description) VALUES (753,'Symbolism allegory mythology and legend',null);
INSERT INTO "integer"("number", name, description) VALUES (754,'Genre paintings',null);
INSERT INTO "integer"("number", name, description) VALUES (755,'Religion',null);
INSERT INTO "integer"("number", name, description) VALUES (756,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (757,'Human figures',null);
INSERT INTO "integer"("number", name, description) VALUES (758,'Other subjects',null);
INSERT INTO "integer"("number", name, description) VALUES (759,'Historical geographic and persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (760,'Graphic arts printmaking and prints',null);
INSERT INTO "integer"("number", name, description) VALUES (761,'Relief processes (Block printing)',null);
INSERT INTO "integer"("number", name, description) VALUES (762,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (763,'Lithographic processes',null);
INSERT INTO "integer"("number", name, description) VALUES (764,'Chromolithography and serigraphy',null);
INSERT INTO "integer"("number", name, description) VALUES (765,'Metal engraving',null);
INSERT INTO "integer"("number", name, description) VALUES (766,'Mezzotinting aquatinting and related processes',null);
INSERT INTO "integer"("number", name, description) VALUES (767,'Etching and drypoint',null);
INSERT INTO "integer"("number", name, description) VALUES (768,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (769,'Prints',null);
INSERT INTO "integer"("number", name, description) VALUES (770,'Photography photographs and computer art',null);
INSERT INTO "integer"("number", name, description) VALUES (771,'Techniques equipment and materials',null);
INSERT INTO "integer"("number", name, description) VALUES (772,'Metallic salt processes',null);
INSERT INTO "integer"("number", name, description) VALUES (773,'Pigment processes of printing',null);
INSERT INTO "integer"("number", name, description) VALUES (774,'Holography',null);
INSERT INTO "integer"("number", name, description) VALUES (775,'Digital photography',null);
INSERT INTO "integer"("number", name, description) VALUES (776,'Computer art (Digital art)',null);
INSERT INTO "integer"("number", name, description) VALUES (777,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (778,'Fields and kinds of photography',null);
INSERT INTO "integer"("number", name, description) VALUES (779,'Photographs',null);
INSERT INTO "integer"("number", name, description) VALUES (780,'Music',null);
INSERT INTO "integer"("number", name, description) VALUES (781,'General principles and musical forms',null);
INSERT INTO "integer"("number", name, description) VALUES (782,'Vocal music',null);
INSERT INTO "integer"("number", name, description) VALUES (783,'Music for single voices the voice',null);
INSERT INTO "integer"("number", name, description) VALUES (784,'Instruments and instrumental ensembles',null);
INSERT INTO "integer"("number", name, description) VALUES (785,'Ensembles with one instrument per part',null);
INSERT INTO "integer"("number", name, description) VALUES (786,'Keyboard and other instruments',null);
INSERT INTO "integer"("number", name, description) VALUES (787,'Stringed instruments',null);
INSERT INTO "integer"("number", name, description) VALUES (788,'Wind instruments',null);
INSERT INTO "integer"("number", name, description) VALUES (789,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (790,'Recreational and performing arts',null);
INSERT INTO "integer"("number", name, description) VALUES (791,'Public performances',null);
INSERT INTO "integer"("number", name, description) VALUES (792,'Stage presentations',null);
INSERT INTO "integer"("number", name, description) VALUES (793,'Indoor games and amusements',null);
INSERT INTO "integer"("number", name, description) VALUES (794,'Indoor games of skill',null);
INSERT INTO "integer"("number", name, description) VALUES (795,'Games of chance',null);
INSERT INTO "integer"("number", name, description) VALUES (796,'Athletic and outdoor sports and games',null);
INSERT INTO "integer"("number", name, description) VALUES (797,'Aquatic and air sports',null);
INSERT INTO "integer"("number", name, description) VALUES (798,'Equestrian sports and animal racing',null);
INSERT INTO "integer"("number", name, description) VALUES (799,'Fishing hunting and shooting',null);
INSERT INTO "integer"("number", name, description) VALUES (800,'Literature and rhetoric',null);
INSERT INTO "integer"("number", name, description) VALUES (801,'Philosophy and theory',null);
INSERT INTO "integer"("number", name, description) VALUES (802,'Miscellany',null);
INSERT INTO "integer"("number", name, description) VALUES (803,'Dictionaries and encyclopedias',null);
INSERT INTO "integer"("number", name, description) VALUES (804,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (805,'Serial publications',null);
INSERT INTO "integer"("number", name, description) VALUES (806,'Organizations and management',null);
INSERT INTO "integer"("number", name, description) VALUES (807,'Education research and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (808,'Rhetoric and collections of literature',null);
INSERT INTO "integer"("number", name, description) VALUES (809,'History description and criticism',null);
INSERT INTO "integer"("number", name, description) VALUES (810,'American literature in English',null);
INSERT INTO "integer"("number", name, description) VALUES (811,'American poetry in English',null);
INSERT INTO "integer"("number", name, description) VALUES (812,'American drama in English',null);
INSERT INTO "integer"("number", name, description) VALUES (813,'American fiction in English',null);
INSERT INTO "integer"("number", name, description) VALUES (814,'American essays in English',null);
INSERT INTO "integer"("number", name, description) VALUES (815,'American speeches in English',null);
INSERT INTO "integer"("number", name, description) VALUES (816,'American letters in English',null);
INSERT INTO "integer"("number", name, description) VALUES (817,'American humor and satire in English',null);
INSERT INTO "integer"("number", name, description) VALUES (818,'American miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (819,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (820,'English and Old English literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (821,'English poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (822,'English drama',null);
INSERT INTO "integer"("number", name, description) VALUES (823,'English fiction',null);
INSERT INTO "integer"("number", name, description) VALUES (824,'English essays',null);
INSERT INTO "integer"("number", name, description) VALUES (825,'English speeches',null);
INSERT INTO "integer"("number", name, description) VALUES (826,'English letters',null);
INSERT INTO "integer"("number", name, description) VALUES (827,'English humor and satire',null);
INSERT INTO "integer"("number", name, description) VALUES (828,'English miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (829,'Old English (Anglo-Saxon)',null);
INSERT INTO "integer"("number", name, description) VALUES (830,'Literatures of Germanic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (831,'German poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (832,'German drama',null);
INSERT INTO "integer"("number", name, description) VALUES (833,'German fiction',null);
INSERT INTO "integer"("number", name, description) VALUES (834,'German essays',null);
INSERT INTO "integer"("number", name, description) VALUES (835,'German speeches',null);
INSERT INTO "integer"("number", name, description) VALUES (836,'German letters',null);
INSERT INTO "integer"("number", name, description) VALUES (837,'German humor and satire',null);
INSERT INTO "integer"("number", name, description) VALUES (838,'German miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (839,'Other Germanic literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (840,'Literatures of Romance languages',null);
INSERT INTO "integer"("number", name, description) VALUES (841,'French poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (842,'French drama',null);
INSERT INTO "integer"("number", name, description) VALUES (843,'French fiction',null);
INSERT INTO "integer"("number", name, description) VALUES (844,'French essays',null);
INSERT INTO "integer"("number", name, description) VALUES (845,'French speeches',null);
INSERT INTO "integer"("number", name, description) VALUES (846,'French letters',null);
INSERT INTO "integer"("number", name, description) VALUES (847,'French humor and satire',null);
INSERT INTO "integer"("number", name, description) VALUES (848,'French miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (849,'Occitan and Catalan literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (850,'Italian Romanian and related literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (851,'Italian poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (852,'Italian drama',null);
INSERT INTO "integer"("number", name, description) VALUES (853,'Italian fiction',null);
INSERT INTO "integer"("number", name, description) VALUES (854,'Italian essays',null);
INSERT INTO "integer"("number", name, description) VALUES (855,'Italian speeches',null);
INSERT INTO "integer"("number", name, description) VALUES (856,'Italian letters',null);
INSERT INTO "integer"("number", name, description) VALUES (857,'Italian humor and satire',null);
INSERT INTO "integer"("number", name, description) VALUES (858,'Italian miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (859,'Romanian and related literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (860,'Spanish and Portuguese literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (861,'Spanish poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (862,'Spanish drama',null);
INSERT INTO "integer"("number", name, description) VALUES (863,'Spanish fiction',null);
INSERT INTO "integer"("number", name, description) VALUES (864,'Spanish essays',null);
INSERT INTO "integer"("number", name, description) VALUES (865,'Spanish speeches',null);
INSERT INTO "integer"("number", name, description) VALUES (866,'Spanish letters',null);
INSERT INTO "integer"("number", name, description) VALUES (867,'Spanish humor and satire',null);
INSERT INTO "integer"("number", name, description) VALUES (868,'Spanish miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (869,'Portuguese literature',null);
INSERT INTO "integer"("number", name, description) VALUES (870,'Italic literatures Latin literature',null);
INSERT INTO "integer"("number", name, description) VALUES (871,'Latin poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (872,'Latin dramatic poetry and drama',null);
INSERT INTO "integer"("number", name, description) VALUES (873,'Latin epic poetry and fiction',null);
INSERT INTO "integer"("number", name, description) VALUES (874,'Latin lyric poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (875,'Latin speeches',null);
INSERT INTO "integer"("number", name, description) VALUES (876,'Latin letters',null);
INSERT INTO "integer"("number", name, description) VALUES (877,'Latin humor and satire',null);
INSERT INTO "integer"("number", name, description) VALUES (878,'Latin miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (879,'Literatures of other Italic languages',null);
INSERT INTO "integer"("number", name, description) VALUES (880,'Hellenic literatures classical Greek',null);
INSERT INTO "integer"("number", name, description) VALUES (881,'Classical Greek poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (882,'Classical Greek dramatic poetry and drama',null);
INSERT INTO "integer"("number", name, description) VALUES (883,'Classical Greek epic poetry and fiction',null);
INSERT INTO "integer"("number", name, description) VALUES (884,'Classical Greek lyric poetry',null);
INSERT INTO "integer"("number", name, description) VALUES (885,'Classical Greek speeches',null);
INSERT INTO "integer"("number", name, description) VALUES (886,'Classical Greek letters',null);
INSERT INTO "integer"("number", name, description) VALUES (887,'Classical Greek humor and satire',null);
INSERT INTO "integer"("number", name, description) VALUES (888,'Classical Greek miscellaneous writings',null);
INSERT INTO "integer"("number", name, description) VALUES (889,'Modern Greek literature',null);
INSERT INTO "integer"("number", name, description) VALUES (890,'Literatures of other languages',null);
INSERT INTO "integer"("number", name, description) VALUES (891,'East Indo-European and Celtic literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (892,'Afro-Asiatic literatures Semitic literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (893,'Non-Semitic Afro-Asiatic literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (894,'Altaic Uralic Hyperborean and Dravidian',null);
INSERT INTO "integer"("number", name, description) VALUES (895,'Literatures of East and Southeast Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (896,'African literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (897,'North American native literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (898,'South American native literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (899,'Austronesian and other literatures',null);
INSERT INTO "integer"("number", name, description) VALUES (900,'History and geography',null);
INSERT INTO "integer"("number", name, description) VALUES (901,'Philosophy and theory',null);
INSERT INTO "integer"("number", name, description) VALUES (902,'Miscellany',null);
INSERT INTO "integer"("number", name, description) VALUES (903,'Dictionaries and encyclopedias',null);
INSERT INTO "integer"("number", name, description) VALUES (904,'Collected accounts of events',null);
INSERT INTO "integer"("number", name, description) VALUES (905,'Serial publications',null);
INSERT INTO "integer"("number", name, description) VALUES (906,'Organizations and management',null);
INSERT INTO "integer"("number", name, description) VALUES (907,'Education research and related topics',null);
INSERT INTO "integer"("number", name, description) VALUES (908,'Kinds of persons treatment',null);
INSERT INTO "integer"("number", name, description) VALUES (909,'World history',null);
INSERT INTO "integer"("number", name, description) VALUES (910,'Geography and travel',null);
INSERT INTO "integer"("number", name, description) VALUES (911,'Historical geography',null);
INSERT INTO "integer"("number", name, description) VALUES (912,'Atlases maps charts and plans',null);
INSERT INTO "integer"("number", name, description) VALUES (913,'Geography of and travel in ancient world',null);
INSERT INTO "integer"("number", name, description) VALUES (914,'Geography of and travel in Europe',null);
INSERT INTO "integer"("number", name, description) VALUES (915,'Geography of and travel in Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (916,'Geography of and travel in Africa',null);
INSERT INTO "integer"("number", name, description) VALUES (917,'Geography of and travel in North America',null);
INSERT INTO "integer"("number", name, description) VALUES (918,'Geography of and travel in South America',null);
INSERT INTO "integer"("number", name, description) VALUES (919,'Geography of and travel in other areas',null);
INSERT INTO "integer"("number", name, description) VALUES (920,'Biography genealogy and insignia',null);
INSERT INTO "integer"("number", name, description) VALUES (921,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (922,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (923,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (924,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (925,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (926,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (927,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (928,'(Optional number)',null);
INSERT INTO "integer"("number", name, description) VALUES (929,'Genealogy names and insignia',null);
INSERT INTO "integer"("number", name, description) VALUES (930,'History of ancient world to ca. 499',null);
INSERT INTO "integer"("number", name, description) VALUES (931,'China to 420',null);
INSERT INTO "integer"("number", name, description) VALUES (932,'Egypt to 640',null);
INSERT INTO "integer"("number", name, description) VALUES (933,'Palestine to 70',null);
INSERT INTO "integer"("number", name, description) VALUES (934,'India to 647',null);
INSERT INTO "integer"("number", name, description) VALUES (935,'Mesopotamia and Iranian Plateau to 637',null);
INSERT INTO "integer"("number", name, description) VALUES (936,'Europe north and west of Italy to ca. 499',null);
INSERT INTO "integer"("number", name, description) VALUES (937,'Italy and adjacent territories to 476',null);
INSERT INTO "integer"("number", name, description) VALUES (938,'Greece to 323',null);
INSERT INTO "integer"("number", name, description) VALUES (939,'Other parts of ancient world to ca. 640',null);
INSERT INTO "integer"("number", name, description) VALUES (940,'History of Europe',null);
INSERT INTO "integer"("number", name, description) VALUES (941,'British Isles',null);
INSERT INTO "integer"("number", name, description) VALUES (942,'England and Wales',null);
INSERT INTO "integer"("number", name, description) VALUES (943,'Central Europe Germany',null);
INSERT INTO "integer"("number", name, description) VALUES (944,'France and Monaco',null);
INSERT INTO "integer"("number", name, description) VALUES (945,'Italian Peninsula and adjacent islands',null);
INSERT INTO "integer"("number", name, description) VALUES (946,'Iberian Peninsula and adjacent islands',null);
INSERT INTO "integer"("number", name, description) VALUES (947,'Eastern Europe Russia',null);
INSERT INTO "integer"("number", name, description) VALUES (948,'Scandinavia',null);
INSERT INTO "integer"("number", name, description) VALUES (949,'Other parts of Europe',null);
INSERT INTO "integer"("number", name, description) VALUES (950,'History of Asia Far East',null);
INSERT INTO "integer"("number", name, description) VALUES (951,'China and adjacent areas',null);
INSERT INTO "integer"("number", name, description) VALUES (952,'Japan',null);
INSERT INTO "integer"("number", name, description) VALUES (953,'Arabian Peninsula and adjacent areas',null);
INSERT INTO "integer"("number", name, description) VALUES (954,'South Asia India',null);
INSERT INTO "integer"("number", name, description) VALUES (955,'Iran',null);
INSERT INTO "integer"("number", name, description) VALUES (956,'Middle East (Near East)',null);
INSERT INTO "integer"("number", name, description) VALUES (957,'Siberia (Asiatic Russia)',null);
INSERT INTO "integer"("number", name, description) VALUES (958,'Central Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (959,'Southeast Asia',null);
INSERT INTO "integer"("number", name, description) VALUES (960,'History of Africa',null);
INSERT INTO "integer"("number", name, description) VALUES (961,'Tunisia and Libya',null);
INSERT INTO "integer"("number", name, description) VALUES (962,'Egypt and Sudan',null);
INSERT INTO "integer"("number", name, description) VALUES (963,'Ethiopia and Eritrea',null);
INSERT INTO "integer"("number", name, description) VALUES (964,'Northwest African coast and offshore islands',null);
INSERT INTO "integer"("number", name, description) VALUES (965,'Algeria',null);
INSERT INTO "integer"("number", name, description) VALUES (966,'West Africa and offshore islands',null);
INSERT INTO "integer"("number", name, description) VALUES (967,'Central Africa and offshore islands',null);
INSERT INTO "integer"("number", name, description) VALUES (968,'Southern Africa Republic of South Africa',null);
INSERT INTO "integer"("number", name, description) VALUES (969,'South Indian Ocean islands',null);
INSERT INTO "integer"("number", name, description) VALUES (970,'History of North America',null);
INSERT INTO "integer"("number", name, description) VALUES (971,'Canada',null);
INSERT INTO "integer"("number", name, description) VALUES (972,'Middle America Mexico',null);
INSERT INTO "integer"("number", name, description) VALUES (973,'United States',null);
INSERT INTO "integer"("number", name, description) VALUES (974,'Northeastern United States',null);
INSERT INTO "integer"("number", name, description) VALUES (975,'Southeastern United States',null);
INSERT INTO "integer"("number", name, description) VALUES (976,'South central United States',null);
INSERT INTO "integer"("number", name, description) VALUES (977,'North central United States',null);
INSERT INTO "integer"("number", name, description) VALUES (978,'Western United States',null);
INSERT INTO "integer"("number", name, description) VALUES (979,'Great Basin and Pacific Slope region',null);
INSERT INTO "integer"("number", name, description) VALUES (980,'History of South America',null);
INSERT INTO "integer"("number", name, description) VALUES (981,'Brazil',null);
INSERT INTO "integer"("number", name, description) VALUES (982,'Argentina',null);
INSERT INTO "integer"("number", name, description) VALUES (983,'Chile',null);
INSERT INTO "integer"("number", name, description) VALUES (984,'Bolivia',null);
INSERT INTO "integer"("number", name, description) VALUES (985,'Peru',null);
INSERT INTO "integer"("number", name, description) VALUES (986,'Colombia and Ecuador',null);
INSERT INTO "integer"("number", name, description) VALUES (987,'Venezuela',null);
INSERT INTO "integer"("number", name, description) VALUES (988,'Guiana',null);
INSERT INTO "integer"("number", name, description) VALUES (989,'Paraguay and Uruguay',null);
INSERT INTO "integer"("number", name, description) VALUES (990,'History of other areas',null);
INSERT INTO "integer"("number", name, description) VALUES (991,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (992,'Unassigned',null);
INSERT INTO "integer"("number", name, description) VALUES (993,'New Zealand',null);
INSERT INTO "integer"("number", name, description) VALUES (994,'Australia',null);
INSERT INTO "integer"("number", name, description) VALUES (995,'Melanesia New Guinea',null);
INSERT INTO "integer"("number", name, description) VALUES (996,'Other parts of Pacific Polynesia',null);
INSERT INTO "integer"("number", name, description) VALUES (997,'Atlantic Ocean islands',null);
INSERT INTO "integer"("number", name, description) VALUES (998,'Arctic islands and Antarctica',null);
INSERT INTO "integer"("number", name, description) VALUES (999,'Extraterrestrial world',null);