<?php


/**
 * Skeleton subclass for representing a row from the 'alumno' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:40 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Alumno extends BaseAlumno {
const ID_GRUPO_ALUMNO=5;
    
    private $__lista;
    
    public function __toString() {
        return ucwords(sprintf("%s %s %s", $this->getNombre(), $this->getAPaterno(), $this->getAMaterno()));
    }
    
    public function __toString2() {
        return ucwords(sprintf("%s %s %s", $this->getAPaterno(), $this->getAMaterno(), $this->getNombre()));
    }
    protected function doSave(PropelPDO $con) {
        if ($this->getNumeroControl() && !AlumnoPeer::getSfGuardUser($this)):
    	    $password = sfGuardUserPeer::doMakePassword($this->getNumeroControl());

            $sf_guard_user = new sfGuardUser;
            $sf_guard_user->setUsername($this->getNumeroControl());
            $sf_guard_user->setPassword($this->getNumeroControl());
            $sf_guard_user->save();

            $sf_user_group = new sfGuardUserGroup;
            $sf_user_group->setUserId($sf_guard_user->getId());
            $sf_user_group->setGroupId(self::ID_GRUPO_ALUMNO);
            $sf_user_group->save();

           // SendMail::sendPasswordForAlumnoMail($this, $password);	
	endif;
        parent::doSave($con);
    }
} // Alumno
