<?php


/**
 * Skeleton subclass for representing a row from the 'book' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:40 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Book extends BaseBook {


	/**
	 * Initializes internal state of Book object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public  function getName()
	{
		return sprintf("%s %s",  $this->getAuthorLastname(), $this->getAuthorFirstname());
	}

	public  function getClasification()
	{
		$decimal = DecimalenPeer::retrieveByPK($this->getIdDecimal());
		$integer = IntegerPeer::retrieveByPK($decimal->getIdInteger());
		//Numero Dewey = $integer->getNumber(), $decimal->getNumber();
		return sprintf("%s | %s", $integer->getName(), $decimal->getName());

	}


	public  function getDeweyn()
	{
		$decimal = DecimalenPeer::retrieveByPK($this->getIdDecimal());
		$integer = IntegerPeer::retrieveByPK($decimal->getIdInteger());

		if (($this->getAuthorLastname() =="")|| (($this->getAuthorLastname() =="anonymous")) || (($this->getAuthorLastname() =="Anonymous")) )
		return sprintf("%s.%s  %s",$integer->getNumber(), $decimal->getNumber(), substr($this->getTitle(), 0, 3)) ;
		else
		return sprintf("%s.%s  %s",$integer->getNumber(), $decimal->getNumber(), substr($this->getAuthorLastname() , 0,3));
	}

}