<?php


/**
 * Skeleton subclass for representing a row from the 'book' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:40 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Book extends BaseBook {

	/**
	 * Initializes internal state of Book object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}



	public  function getName()
	{
		return sprintf("%s %s",  $this->getAuthorLastname(), $this->getAuthorFirstname());
	}
	public  function getClasificacion()
	{
		$decimal = DecimalenPeer::retrieveByPK($this->getIdDecimal());
		$integer = IntegerPeer::retrieveByPK($decimal->getIdInteger());
		if($integer->getNumber()<10)
			return sprintf("00%s.%s %s %s",$integer->getNumber(), $decimal->getNumber(), $integer->getName(), $decimal->getName());
		elseif ($integer->getNumber()<100)
			return sprintf("0%s.%s %s %s",$integer->getNumber(), $decimal->getNumber(), $integer->getName(), $decimal->getName());
		elseif($integer->getNumber()<100)
			return sprintf("%s.%s %s %s",$integer->getNumber(), $decimal->getNumber(), $integer->getName(), $decimal->getName());

	}	

} // Book
/*if (var_dump($this->getDecimalen()->getInteger()<10)
        return sprintf("00%s.%s. %s -> %s", $this->getInteger()->getNumber(), $this->getNumber(), $this->getInteger()->getName(), $this->getName());
    	else if ($this->getInteger()->getName()<100)
    	return sprintf("0%s.%s. %s -> %s", $this->getInteger()->getNumber(), $this->getNumber(), $this->getInteger()->getName(), $this->getName());
    	else
    	return sprintf("%s.%s. %s -> %s", $this->getInteger()->getNumber(), $this->getNumber(), $this->getInteger()->getName(), $this->getName());	*/