<?php

/**
 * Skeleton subclass for representing a row from the 'decimalen' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:41 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Decimalen extends BaseDecimalen {

	public function __toString() {
			return sprintf("%s.%s %s | %s",  $this->getInteger()->getNumber(),$this->getNumber(),$this->getInteger()->getName(), $this->getName());
    }

    public function getDecimal()
	{
		return sprintf(".%s",  $this->getNumber());
	}

	public function getIdInteger()
	{
		if (($this->id_integer)<10)
			return sprintf("00%s %s",  $this->id_integer, $this->getInteger()->getName());
		elseif (($this->id_integer)<100)
			return sprintf("0%s %s",  $this->id_integer, $this->getInteger()->getName());
		elseif (($this->id_integer)<1000)
			return sprintf("%s %s",   $this->id_integer, $this->getInteger()->getName() );
	}

} // Decimalen
