<?php


/**
 * Skeleton subclass for representing a row from the 'entero' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:41 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Entero extends BaseEntero {

	public function __toString() {
			return sprintf("%s %s",   $this->getNumero(), $this->getNombre());
    }

    public function getNumber()
	{
		if (($this->numero)<10)
			return sprintf("00%s", $this->numero);
		elseif (($this->numero)<100)
			return sprintf("0%s",  $this->numero);
		elseif (($this->numero)<1000)
			return sprintf("%s",   $this->numero);
	}

} // Entero
