<?php


/**
 * Skeleton subclass for performing query and update operations on the 'folio_control' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jan 16 01:16:05 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FolioControlPeer extends BaseFolioControlPeer {

	static public function getFolioByYear($year, $conn) {
        $c = new Criteria;

        $c->add(self::ANNO, $year, Criteria::EQUAL);

        if (self::doCount($c, $conn)) :
            $obj = self::doSelectOne($c, $conn);
        else:
            $obj = new FolioControl;
            $obj->setAnno($year);
            $obj->save($conn);
        endif;

        $folio = $obj->getConsecutivo();
        $obj->setConsecutivo(++$folio);
        $obj->save($conn);

        return $folio;
    }

} // FolioControlPeer
