<?php


/**
 * Skeleton subclass for representing a row from the 'integer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:41 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Integer extends BaseInteger {

	public function __toString() {
		
			return sprintf("%s %s",   $this->getNumber(), $this->getName());
    }

    public function getNumber()
	{
		if (($this->number)<10) 
			return sprintf("00%s", $this->number);
		elseif (($this->number)<100) 
			return sprintf("0%s",  $this->number);
		elseif (($this->number)<1000) 
			return sprintf("%s",   $this->number);
	}

} // Integer
