<?php


/**
 * Skeleton subclass for representing a row from the 'libro' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:42 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Libro extends BaseLibro {

	/**
	 * Initializes internal state of Libro object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public  function getNombrecompleto()
	{
		return sprintf("%s %s %s",  $this->getApaternoAutor(), $this->getNombreautor(), $this->getAmaternoAutor());
	}
	public  function getClasificacion()
	{
		$decimal = DecimalPeer::retrieveByPK($this->getIdDecimal());
		//$integer = EnteroPeer::retrieveByPK($decimal->getIdEntero());
		//Numero Dewey = $integer->getNumber(), $decimal->getNumber();
		return sprintf("%s", $decimal);
	}
	public  function getFot()
	{
		if($this->getFoto()==null){
			$this->setFot(false);
			return false;
		}
		else{
			$this->setFot(true);
		    return true;
		}
	}

	public  function getDewey()
	{
		$decimal = DecimalPeer::retrieveByPK($this->getIdDecimal());

		if (($this->getApaternoAutor() =="") | (($this->getNombreautor() =="Anónimo")) | ($this->getNombreautor() =="Anonimo") )
			if ($this->getTomo()=='')
					return sprintf("%s.%s  %s",$decimal->getEntero()->getNumero(),$decimal->getNumero(), substr($this->getTitulo(), 0, 3)) ;
		else
			    return sprintf("%s.%s  %s Tomo %s",$decimal->getEntero()->getNumero(),$decimal->getNumero(), substr($this->getTitulo(), 0, 3), $this->getTomo()) ;
		elseif ($this->getTomo()=='')
				return sprintf("%s.%s %s ",$decimal->getEntero()->getNumero(),$decimal->getNumero(), substr($this->getApaternoAutor() , 0,3));
			else
				return sprintf("%s.%s %s  Tomo %s",$decimal->getEntero()->getNumero(),$decimal->getNumero(), substr($this->getApaternoAutor() , 0,3), $this->getTomo());
	}


} // Libro
