<?php


/**
 * Skeleton subclass for performing query and update operations on the 'lista' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:42 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ListaPeer extends BaseListaPeer {


/**
     * Devuelve los cursos a los que esta inscrito un Alumno en el periodo especificado.
     *
     * @param Alumno El alumnos del que se estan solicitando los cursos.
     * @param Periodo $periodo El periodo que se esta consultado.
     * @return Criteria
     */
    static public function getListasForAlumnoCriteria(Alumno $obj, Periodo $periodo = null, $related = false) {
        $c = new Criteria;

        $c->add(self::ID_ALUMNO, $obj->getId(), Criteria::EQUAL);

        if (!is_null($periodo)) :
            $keys = array();
            $keys[] = $periodo->getId();

            $c->add(self::ID_CURSO, $keys, Criteria::IN);

        endif;

        return $c;
    }

    static public function getListaForCursoCriteria(Curso $obj) {
        $c = new Criteria;

        $c->add(self::ID_CURSO, $obj->getId(), Criteria::EQUAL);

        return $c;
    }
} // ListaPeer
