<?php


/**
 * Skeleton subclass for representing a row from the 'materia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov  6 19:23:38 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Materia extends BaseMateria {

	/**
	 * Initializes internal state of Materia object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
public function __toString() {
        return sprintf("%s | %s Semestre", $this->getNombre(),$this->getSemestre());
    }

} // Materia
