<?php


/**
 * Skeleton subclass for representing a row from the 'producto_tienda' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Nov 22 13:48:51 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProductoTienda extends BaseProductoTienda {

	public function __toString() {
			return sprintf("%s",  $this->getNombre());
    }
} // ProductoTienda
