<?php


/**
 * Skeleton subclass for performing query and update operations on the 'profesor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:02:42 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProfesorPeer extends BaseProfesorPeer {

static public function getSfGuardUser(Profesor $profesor){
        $c = new Criteria;
        
        $c->add(sfGuardUserPeer::USERNAME, $profesor->getRfc(), Criteria::EQUAL);
        
        return sfGuardUserPeer::doSelectOne($c);
    }
    
    static public function getProfesoresActivosCriteria() {
        $c = new Criteria;

        $c->add(self::ACTIVO, true, Criteria::EQUAL);

        return $c;
    }

  static public function getProfesorByRFC($rfc) {
        $c = new Criteria;

        $c->add(self::RFC, $rfc, Criteria::EQUAL);
        return $c;
    }
} 