<?php


/**
 * Skeleton subclass for representing a row from the 'segundosumario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct 10 18:41:17 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Segundosumario extends BaseSegundosumario {

	public function __toString() {
        return sprintf("%s, %s, %s", $this->getPrimersumario(), $this->getNumero(), $this->getNombre());
    }
} // Segundosumario
