generator:
  class: sfPropelGenerator
  param:
    model_class:           Integer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Integer
    plural:                Integers
    route_prefix:          integer
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        number:        { label: Dewey Number }
      list:
        title: Catalogue of Dewey Numbers (Integer)
        display: [number, name, description]
        max_per_page: 50
      filter:
        display: [number, name]
      form:    ~
      edit:
        title: Edit the number  %%number%% 
      new:
        title: New number