generator:
  class: sfPropelGenerator
  param:
    model_class:           EmpleadoTienda
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              EmpleadoTienda
    plural:                EmpleadoTiendas
    route_prefix:          empleado_tienda
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
