generator:
  class: sfPropelGenerator
  param:
    model_class:           Book
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Book
    plural:                Books
    route_prefix:          book
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:
        title: Capturar nuevo libro
