default:
  is_secure: true
  credentials: [[administrador, bibliotecario, becabiblioteca,profesor,alumnos,academico]]
delete:
  is_secure: true
  credentials: [[administrador, bibliotecario,admin]]
edit:
  is_secure: true
  credentials: [[administrador, bibliotecario,admin]]