generator:
  class: sfPropelGenerator
  param:
    model_class:           Decimalen
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Decimalen
    plural:                Decimalens
    route_prefix:          decimalen
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        number:        { label: Decimal number }
        id_integer:    { label: General Dewey }
        name:          { label: Decimal name }
      list:    
        title: Catalog of Sub-catego Dewey decimal
        display: [id_integer, =decimal, name, description]
        max_per_page: 50
      filter:  
        display: [id_integer,number, name]
      form:    ~
      edit:    
        title: Edit the number %%id_integer%%.%%number%% 
      new:     
        title: New subcategoria (Decimal)
