<?php
class AlumnoOracionForm extends AlumnoForm {
    public function configure() {
        parent::configure();
        unset($this['id_medio'],
      $this['nombre'         ],
      $this['a_paterno'      ],
      $this['a_materno'      ],
      $this['sexo'           ],
      $this['direccion'      ],
      $this['colonia'        ],
      $this['ciudad'         ],
      $this['estado'         ],
      $this['cp'             ],
      $this['pais'           ],
      $this['telefono'       ],
      $this['celular'        ],
      $this['e_mail'         ],
      $this['fecha_nacimiento'],
      $this['estado_civil'   ],
      $this['padres_nombres' ],
      $this['padres_direccion'],
      $this['padres_colonia' ],
      $this['padres_ciudad'  ],
      $this['padres_estado'  ],
      $this['padres_cp'      ],
      $this['padres_pais'    ],
      $this['padres_telefono'],
      $this['padres_celular' ],
      $this['padres_email'   ],
      $this['pastor_nombre'  ],
      $this['pastor_direccion'],
      $this['pastor_colonia' ],
      $this['pastor_ciudad'  ],
      $this['pastor_estado'  ],
      $this['pastor_cp'      ],
      $this['pastor_pais'    ],
      $this['pastor_telefono'],
      $this['pastor_celular' ],
      $this['pastor_email'   ],
      $this['iglesia_nombre' ],
      $this['iglesia_direccion'],
      $this['iglesia_colonia'],
      $this['iglesia_ciudad' ],
      $this['iglesia_estado' ],
      $this['iglesia_cp'     ],
      $this['iglesia_pais'   ],
      $this['iglesia_telefono'],
      $this['iglesia_email'  ],
      $this['iglesia_web'    ],
      $this['emergencia_nombre'],
      $this['emergencia_direccion'],
      $this['emergencia_colonia'],
      $this['emergencia_ciudad'],
      $this['emergencia_estado'],
      $this['emergencia_telefono'],
      $this['emergencia_celular'],
      $this['fecha_conversion'],
      $this['fecha_bautismo' ],
      $this['fecha_llamamiento'          ],
      $this['testimonio_salvacion'       ],
      $this['testimonio_llamado'         ],
      $this['actividades_iglesia'        ],
      $this['primaria_nombre'            ],
      $this['primaria_ciudad'            ],
      $this['primaria_final' ],
      $this['secundaria_nombre'          ],
      $this['secundaria_ciudad'          ],
      $this['secundaria_final'           ],
      $this['prepa_nombre'   ],
      $this['prepa_ciudad'   ],
      $this['prepa_final'    ],
      $this['otra_nombre'    ],
      $this['otra_ciudad'    ],
      $this['otra_fecha'     ],
      $this['insti_nombre'   ],
      $this['insti_ciudad'   ],
      $this['insti_fecha'    ],
      $this['drogas'         ],
      $this['alcohol'        ],
      $this['medicina_especial'          ],
      $this['medicamento_actual'         ],
      $this['situacion_medica'           ],
      $this['trabajo_secular'            ],
      $this[ 'numero_control'            ],
      $this['inscrito'       ],
      $this['foto'           ],
      $this['recomendacion_pastor'       ],
      $this['preparatoria_pastor'        ],
      $this['carta_recomedacion_hermano' ],
      $this['certificado_medico'         ],
      $this['acta_nacimiento'            ],
      $this['fotografias'    ],
      $this['acta_matrimonio'            ]);
}
}
?>
