generator:
  class: sfPropelGenerator
  param:
    model_class:           Periodo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Periodo
    plural:                Periodos
    route_prefix:          periodo
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        periodo: { label: "Periodo" }
      list:
        title: false
        display: [=periodo, nombre_corto]
        batch_actions: {}
        object_actions: {}
        max_per_page: 20
        actions:
          _new:
            label: Agregar periodo
      filter:    ~
      form:    ~
      edit:
        title: false
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver