default:
  is_secure: true
  credentials: [[alumno, profesor,secretaria]]
edit:
  is_secure: true
  credentials: [[admin,bibliotecario, biblioteca]]
delete:
  is_secure: true
  credentials: [[admin,bibliotecario, biblioteca]]
new:
  is_secure: true
  credentials: [[admin,bibliotecario, biblioteca]]