generator:
  class: sfPropelGenerator
  param:
    model_class:           Entero
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Entero
    plural:                Enteros
    route_prefix:          entero
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        numero:        { label: Numero Dewey }
        descripcion:   { label: Descripción}
      list:    
        title: Catalogo de numeración Dewey
        display: [numero, nombre, descripcion]
        max_per_page: 50
      filter:  
        display: [numero, nombre ]
      form:    ~
      edit:    
        title: Editar el numero  %%numero%% 
      new:     
        title: Nuevo numero