generator:
  class: sfPropelGenerator
  param:
    model_class:           Curso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Curso
    plural:                Cursos
    route_prefix:          curso_curso_secretaria
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
