generator:
  class: sfPropelGenerator
  param:
    model_class:           Materia
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Materia
    plural:                Materias
    route_prefix:          materia
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        nombre: { label: "Nombre de la materia" }
      list:
        title: false
        display: [=nombre, semestre, clave, activo]
        batch_actions: {}
        object_actions: {}
        max_per_page: 20
        actions:
          _new:
            label: Agregar Materia
      filter:
        display: [nombre, semestre, clave, activo]
      form:    ~
      edit:
        title: false
        actions:
          _save:
            label: Guardar
          _delete:
            label: Eliminar
          _list:
            label: Volver
      new:
        title: false
        actions:
          _save:
            label: Guardar
          _save_and_add:
            label: Guardar y Agregar otro
          _list:
            label: Volver